### ISSUE TITLE
Renderer warning: .then() only accepts functions

### ISSUE THREAD

**Issue by r4zzz4k** [electron-userland/electron-webpack#10]
Hey @develar, great job on this tooling! I'm looking forward for first release and for your cooperation with Greg on this!

While trying out `electron-webpack` I'm constantly getting the following message if I run `yarn dev`:
```
┏ Renderer -------------------

  (node:26348) Warning: .then() only accepts functions but was passed: [object Undefined], [object Undefined]

┗ ----------------------------
```
No stack trace emitted, `process.traceProcessWarnings = true` didn't help.
I've tried to boil it down to minimal example and got to [the following state](https://github.com/r4zzz4k/electron-webpack-test). So it seems to not be related to anything external like Vue, TypeScript, only the `electron-webpack dev` command itself. Also, app package prepared by `electron-builder` also doesn't seem to emit this warning.

Unfortunately I'm not that experienced in Node.js / Electron development so I wasn't able to properly debug the issue -- didn't manage to set debugger breakpoints in bluebird module.

Do you have any thoughts?

**Comment by develar** [comment]
Yech, I also see this warn. Related to node HMR. Doesn't harm, but annoying. I will investigate what's wrong. Thanks for clear report.

**Comment by r4zzz4k** [comment]
Thanks for fast response! I looked into it while investigating other issue and didn't understand at first that it's unrelated and actually didn't harm.
