### ISSUE TITLE
Can not find module react when using html-webpack-plugin

### ISSUE THREAD

**Issue by houssemDevs** [electron-userland/electron-webpack#101]
I setup an electron application using react, redux, and bootstrap. the electron-webpack work very well until I wanted to use a custom html file to add support for bootstrap (responsive meta tag), 

I added a custom config file to use my html template with html-webpack-plugin 

webpack.config.renderer.js:

```javascript
const path = require('path');
const htmlwp = require('html-webpack-plugin');

const config = {
    template: path.resolve(__dirname, 'src', 'renderer', 'index.html'),
};

module.exports = {
    plugins: [
        new htmlwp(config)
    ]
};
```

and tell electron-webpack to use by adding settings to package.json:

```json
"electronWebpack": {
    "renderer": {
      "webpackConfig": "webpack.config.renderer.js"
    }
  }
```

Error in electron console:

```
module.js:485 Uncaught Error: Cannot find module 'react'
    at Module._resolveFilename (module.js:485)
    at Function.Module._resolveFilename (D:\Projects\MailSolution\node_modules\electron\dist\resources\electron.asar\common\reset-search-pat…:35)
    at Function.Module._load (module.js:437)
    at Module.require (module.js:513)
    at require (internal/module.js:11)
    at eval (external "react"?3c62:1)
    at Object.react (renderer.js:969)
    at __webpack_require__ (renderer.js:680)
    at fn (renderer.js:90)
    at eval (index.js:2)
```

**Comment by Gum-Joe** [comment]
@houssemDevs similar situation here

**Comment by houssemDevs** [comment]
It would be easy if we can get something like 
```
"electronWebpack": {
    "renderer": {
      "template": "path/to/custom/index.html",
      ...
     }
  }
```

**Comment by Gum-Joe** [comment]
@houssemDevs Me and @loopmode had a look at that, but there was a comment on the code saying that allowing a template is not a good idea. :(

**Comment by houssemDevs** [comment]
@Gum-Joe the meta tags are required by bootstrap, maybe you can include it in the default template ?.

**Comment by Gum-Joe** [comment]
Hmmm
Will try to get a custom template enabled.

**Comment by houssemDevs** [comment]
@Gum-Joe certainly it does not cover all use cases, but enabling bootstrap will certainly cover a lot of use cases.
your effort are highly appreciated.

**Comment by Gum-Joe** [comment]
@houssemDevs Thanks.

**Comment by loopmode** [comment]
@houssemDevs If it's "just" about the meta tag, it might be enough to set it from JS code?
In case of a react app, you could try something like https://github.com/nfl/react-helmet#example 
I am sure something similar exists for vue.
Otherwise, it could always be something like:
```
const meta = document.createElement('meta')
meta.setAttribute('name', 'viewport');
meta.setAttribute('content', 'width=device-width, initial-scale=1, shrink-to-fit=no');
document.head.appendChild(meta);
```
(Not tested, but you get the idea)

**Comment by houssemDevs** [comment]
@Gum-Joe yes it's just about the meta tag for bootstrap. Thank you it's a nice workaround to support bootstrap. and still using the magic of electron-webpack.

**Comment by Gum-Joe** [comment]
@houssemDevs no need to give me credit - @loopmode should get the credit!

**Comment by loopmode** [comment]
😃

**Comment by houssemDevs** [comment]
@Gum-Joe  thank you both for your efforts, and thank you @loopmode  for your nice workaround.

**Comment by Gum-Joe** [comment]
Anytime :)

**Comment by houssemDevs** [comment]
I will change the issue title to 'Adding support to bootstrap responsive meta tag' to reflect the workaround and close it.

**Comment by loopmode** [comment]
@Gum-Joe Actually I'm not sure about this!

I was just about to describe that allowing custom html templates might not be the way to go. 
The topic was discussed or touched already in various different issues, but the solution was basically always what we just did here: Accept that index.html is "not available" to us and consider it as just "the DOM provider", and use javascript powers to do whatever you need in the DOM. I mean.. it's all there. The head, the body, and we have scripting powers. Why should we bother with writing html?
That's how I understood @develar and that's also my opinion. And it was the reason why develar wouldn't implement functionality for custom html templates.

But now that you mentioned it.. I totally forgot that, the config change I suggested to you once, basically worked and you were able to use a custom html template..

So.. Not sure. But looking at this issue and it's title... It started about not finding react, became about adding a meta-tag for bootstrap, then became about custom html template :D
I would rather close it and create more concrete issues again when needed.

**Comment by Gum-Joe** [comment]
@loopmode We should probably close it until we come to some decision as to what to do.
