### ISSUE TITLE
NODE_ENV in webpack.renderer.additions.js

### ISSUE THREAD

**Issue by chapa** [electron-userland/electron-webpack#105]
I'd like to use `process.env.NODE_ENV` in the webpack.renderer.additions.js file I specify in the `"electronWebpack"` part of my package.json, but the value is only defined in development.

Here's an extract of my package.json :
```json
{
  "scripts": {
    "dev": "electron-webpack dev",
    "compile": "electron-webpack",
    "compile2": "NODE_ENV=production electron-webpack"
  },
  "electronWebpack": {
    "renderer": {
      "webpackConfig": "webpack.renderer.additions.js"
    }
  }
}
```

My webpack.renderer.additions.js :
```js
console.log(process.env.NODE_ENV)
module.exports = {}
```

And the results are "development" with `yarn dev`, "undefined" with `yarn compile` and "production" with `yarn compile2`

I even try to add "NODE_ENV=production" at the beginning the `dev` script but it doesn't change the result, I suppose it's not the same context.

So here are my questions :
* Is this a normal behaviour ?
* I need this value in this file, is it ok to add "NODE_ENV=production" at the beginning the `compile` script, or is it just a side effect that works by chance ?

Thank's !

**Comment by loopmode** [comment]
Hi
I simply used `const isProduction = process.env.NODE_ENV !== 'development'` or `const isDevelopment = process.env.NODE_ENV; /* ... */ if (!isDevelopment) { /*...*/ }`
Could that work for you as well?

**Comment by chapa** [comment]
Yes it works, but is it really the right way to do ?
I mean, wouldn't it be better if webpack-electron provided the value "production" in the process.env.NODE_ENV variable (as the dev command does) ?

However, I'm facing another problem I can't figure out this time.
I can't manage to have a development environment for the dll command (even with `NODE_ENV=development webpack-electron dll`), is there any way to do that ?
Maybe should I open a new issue for that ?

**Comment by loopmode** [comment]
Should be a separate issue indeed.

I understand `process.env` as an object that contains values sent to the process/app when started. So it's "natural" that there isn't anything for `NODE_ENV` - unless you launched your app with a `NODE_ENV` value of course. Only then would I "expect" to find the value.

Try printing the contents of process.env, then build a production app and have a look. I was sursprised. (e.g. `console.log(JSON.stringify(process.env, null, 4))` or `<pre>{JSON.stringify(process.env, null, 4)}</pre>`. 
Lot's of stuff, and kind of accurate. Suddently I understood why there is no NODE_ENV :)

**Comment by chapa** [comment]
Sorry for the late reply...

You're right, `NODE_ENV` has nothing to do in the `process.env` of the app.
But what I'm talking about is the `webpack.renderer.additions.js` file, it's not the same context as the application code.
This file is interpreted by nodejs when webpack is "bundling" the application code, so I think it's relevant to have the `NODE_ENV` there.

But frankly it's not a real problem so I'll close this issue. And if another perfectionist comes through here, let him feel free to reopen that issue ;-)

**Comment by trusktr** [comment]
related: https://github.com/electron-userland/electron-webpack/issues/271
