### ISSUE TITLE
Webpack 4

### ISSUE THREAD

**Issue by yovanoc** [electron-userland/electron-webpack#111]
Just to know if the upgrade to webpack 4 is planned? thanks

**Comment by develar** [comment]
Yes.

**Comment by develar** [comment]
Any reason why are you interested?

**Comment by yovanoc** [comment]
Because I really like your project (electron-webpack) and I have a big project on it. (nearly 33k lines of code) and I want to test if there is a lot a difference with Webpack 3 and Webpack 4.
Have you an idea so when will be the upgrade?

**Comment by develar** [comment]
If will be no major issues, maybe tomorrow.

**Comment by yovanoc** [comment]
Ok thanks close this issue when it’s done si I get notified! Thanks a lot for this !

**Comment by loopmode** [comment]
wow, no issues regarding DLLs with webpack 4? I shall study this commit. I definitely had breaking issues with DLL setup after upgrade in another project (not related to electron)

**Comment by develar** [comment]
@loopmode DLL not checked yet ;)

**Comment by loopmode** [comment]
Hah, I thought you were implicitly creating/using DLLs..? So if it "runs", everything is ok..?

**Comment by develar** [comment]
quick start works. Also, I haven't checked hot reload.
