### ISSUE TITLE
How can I define Module Resolution in electron-webpack?

### ISSUE THREAD

**Issue by Dominic-Preap** [electron-userland/electron-webpack#112]
How can I define Module Resolution in electron-webpack?

tsconfig.json
```json
{
  "extends": "./node_modules/electron-webpack/tsconfig-base.json",
  "compilerOptions": {
     ....
    "baseUrl": ".",
    "paths": {
      "@components/*": ["src/renderer/components/*"],
      "@common/*": ["src/renderer/common/*"],
    }
  }  
}
```

App.js
```ts
import { RoutePaths } from '@common/utils';
import { Splashscreen } from '@components/Image';
import { Overlay } from '@components/Overlay';
import { AppRoutes } from '@components/Route';
```
![capture](https://user-images.githubusercontent.com/14802170/37584813-86036a68-2b89-11e8-8670-bc0aef9b9948.PNG)

**Comment by chapa** [comment]
Hi,

I'm not familiar with TypeScript so I don't know exactly the purpose of `tsconfig.json` file, but I think it's more at the webpack configuration level you should look at.

[The doc](https://webpack.electron.build/modifying-webpack-configurations) explains how to add some custom configuration to webpack, and the [resolve.alias](https://webpack.js.org/configuration/resolve/#resolve-alias) option should solve your problem ;-)

**Comment by Dominic-Preap** [comment]
@chapa  
I just updated `webpack.renderer.additions.js` and it works. Thank you. By the way `tsconfig.json` just make your IDE know where the import files are coming from.
```js
const path = require('path');
module.exports = {
  resolve: {
    alias: {
      '@components': path.resolve(__dirname, 'src/renderer/components'),
      '@common': path.resolve(__dirname, 'src/renderer/common')
    }
  } 
};

```
