### ISSUE TITLE
“__static” not work as expected in production

### ISSUE THREAD

**Issue by zeng450026937** [electron-userland/electron-webpack#114]
“__static” is still setted to projectDir/static in renderer process, while pointing to resourceDir/static in main process.

**Comment by ctotheameron** [comment]
I'm experiencing the same issue in my project.

logging __static in main process shows:
/Volumes/<my volume name>/<my app name>.app/Contents/Resources/static/

logging __static in render process shows:
/Users/<me>/workspace/<my project dir>/static

**Comment by christophpre** [comment]
I think this issue can be resolved now. Since the fix is already contained in version 2.3.0
