### ISSUE TITLE
Adding new loader to modules.rules does not work with custom config

### ISSUE THREAD

**Issue by franconob** [electron-userland/electron-webpack#116]
I've extended webpack configuration by creating a new file, webpack.common.js. I want to add a new loader. The problem is that if I add the loader to module.loaders (which is already a deprecated setting in webpack), it works, but it doesn't if I add the loader to module.rules. 

Is this an issue related to webpack-merge? To webpack version?

electron-webpack: 1.13.0

**Comment by loopmode** [comment]
very strange. This worked for me just fine:
```
module.exports = {
    module: {
        rules: [
            {
                test: /\.(frag|vert|obj|dae)$/,
                use: 'raw-loader'
            }
        ]
    }
};

```

**Comment by loopmode** [comment]
Also, please note that it's `module`, not `modules`

**Comment by franconob** [comment]
Hi @loopmode, thanks for the comment. I forgot to mention that this actually works when a run the app using `electron-webpack dev`, but it doesn't work when I create and execute the packaged version of the app. Tha's weirder indeed. Can I provide more infor about this?

Thanks.

**Comment by franconob** [comment]
Closing issue, I will reopen it in the future if necessary.

Thanks!
