### ISSUE TITLE
typescript loader not working (version incompatibility)

### ISSUE THREAD

**Issue by jh3141** [electron-userland/electron-webpack#118]
To reproduce:

* clone electron-webpack-quit-start (I got commit #f5fdcfb when I did this)
* run `yarn` to install modules
* run `yarn add typescript electron-webpack-ts --dev` and create `tsconfig.json` as suggested at https://webpack.electron.build/add-ons#typescript
* rename `src/main/index.js` to `src/main/index.ts` and change line 10 to `let mainWindow : BrowserWindow|null` (to remove type error).
* run `electron-webpack dev`.

Result is:

```
┏ Main -----------------------

  Hash: 3039a570b6828b478494
  Version: webpack 3.11.0
  Time: 2499ms
    Asset     Size  Chunks  Chunk Names
  main.js  32.1 kB       0  main
  [./node_modules/electron-webpack/out/electron-main-hmr/main-hmr.js] ./node_modules/electron-webpack/out/electron-main-hmr/main-hmr.js 559
bytes {0} [built]
  [./src/main/index.ts] ./src/main/index.ts 320 bytes {0} [built] [failed] [1 error]
  [electron-webpack/out/electron-main-hmr/HmrClient] external "electron-webpack/out/electron-main-hmr/HmrClient" 42 bytes {0} [not cacheable
]
  [source-map-support/source-map-support.js] external "source-map-support/source-map-support.js" 42 bytes {0} [not cacheable]
     [0] multi ./node_modules/electron-webpack/out/electron-main-hmr/main-hmr ./src/main/index.ts 40 bytes {0} [built]

  ERROR in ./src/main/index.ts
  Module build failed: TypeError: Cannot set property 'tsLoaderFileVersion' of undefined
      at successLoader (C:\Development\electronic\alarm2\node_modules\ts-loader\dist\index.js:47:54)
      at Object.loader (C:\Development\electronic\alarm2\node_modules\ts-loader\dist\index.js:21:12)
   @ multi ./node_modules/electron-webpack/out/electron-main-hmr/main-hmr ./src/main/index.ts

┗ ----------------------------
```

According to https://github.com/TypeStrong/ts-loader/issues/748 this is a result of an incompatibility between webpack 3 and ts-loader 4; as webpack 3 is being used in the project, ts-loader 3 must be used.  However it seems that the typescript module here has been upgraded to use ts-loader 4 while the version of the main electron-webpack module deployed on the boilerplate is still using webpack 3.

**Comment by develar** [comment]
electron-webpack 2.0.1 is now latest release.

**Comment by jh3141** [comment]
... so shouldn't it be used in the quick start repository?

**Comment by develar** [comment]
Fixed as part of this request — https://github.com/electron-userland/electron-webpack-quick-start/commit/135f9f34b48e6097260ea382a39126495fb50ab7
