### ISSUE TITLE
Support for React?

### ISSUE THREAD

**Issue by derwaldgeist** [electron-userland/electron-webpack#12]
First of all: thanks a lot for making this, it is very promising, especially due to its tight integration with electron-builder!

My app is based on React, but the current configuration doesn't seem to support this. If I try to include electron-webpack, it complains invalid tokens in JSX files. Is there a chance to create a React adapter for electron-webpack? 

BTW: It would also be fantastic if Sass was supported.

**Comment by develar** [comment]
> Is there a chance to create a React adapter for electron-webpack?

We officially recommends https://github.com/chentsulin/electron-react-boilerplate

cc @amilajack 

https://github.com/chentsulin/electron-react-boilerplate/issues/1000#issuecomment-325304300

Do you consider to use `electron-react-boilerplate`? Is it suitable for your needs?

It is very easy to add support for JSX. But "bundling" is just a one piece from story. Maybe, complete boilerplate will be better for you.

**Comment by andyfangdz** [comment]
I would like to thank @amilajack and @chentsulin for your hard work on `electron-react-boilerplate`. However, as it currently stands, `electron-react-boilerplate` is too heavy for starting a simple new project, and I have tried to peel off many of the dependencies I'm not using in that template myself. I think the minimal approach taken in `electron-webpack` is going to be very helpful.

**Comment by develar** [comment]
> is too heavy for starting a simple new project

Yeach... the same feelings. I have also tried to use this boilerplate, but finally decided to use Vue.js (https://github.com/SimulatedGREG/electron-vue).

Ok, I hope @amilajack will not mind and in the end maybe electron-react-boilerplate will use electron-webpack (because no need to reimplement basic webpack lib each time). For now basic support will be added. And maybe basic will be enough (as in case of Vue).

**Comment by SimulatedGREG** [comment]
I haven't personally used the electron-react-boilerplate, but I have taken some inspiration from it when making electron-vue. I can agree with @andyfangdz that it is very heavy or could be considered *bloated*. One major drawback I know is that it still uses a 2 `package.json` setup. I think it would be very beneficial to create a React add-on @develar and is probably inevitable.

**Comment by derwaldgeist** [comment]
I made two attempts to incorporate electron-react-boilerplate and always gave up and tried to find another, more lightweight solution. Sure, it is quite sophisticated, but the docs are outdated (and even contradictory in some points), and it contains a lot of stuff I don't need (like Flow).

But the main point why I didn't use it was that it did only have documentation on how to setup the main process but not about how you would pack additional renderer windows. I was hoping that electron-webpack would offer me a way easier access to it.

Anyways, since electron-webpack did not support React at the moment, I ended up using
https://github.com/jschr/electron-react-redux-boilerplate
which was a lot easier to incorporate my existing app.

**Comment by develar** [comment]
Sass supported in the 1.2.0.  https://webpack.electron.build/languages-and-frameworks#sass

**Comment by develar** [comment]
React supported in the 1.3.0. Simply `yarn add babel-preset-react --dev` to enable React support.

I am not React user, and don't know, is it enough for first-class react support. Feel free to ask, if need, we can introduce special preset (as we do for vue and typescript). For now, as there is the only dependency, preset is not required.

@pronebird What do you think about using electron-webpack under the hood?

**Comment by pronebird** [comment]
@develar I generally stay away from Webpack. I believe that `babel-preset-react` and few tweaks to `.eslintrc` and `.babelrc` should be sufficient.

**Comment by develar** [comment]
In case of webpack and little help from electron-webpack you get hmr for main an renderer code :) https://medium.com/@develar/electron-very-fast-developer-workflow-with-webpack-hmr-e2a2e23590ad?source=linkShare-7f265b3d5853-1504112369

**Comment by SimulatedGREG** [comment]
@develar 

I just remembered that it might be beneficial to install [`react-devtools`](https://github.com/facebook/react-devtools) and possibly [`redux-devtools`](https://github.com/gaearon/redux-devtools). `electron-devtools-installer` has Ids for both of them, so it could be implemented the same way `vue-devtools` currently is. Thoughts @derwaldgeist, @andyfangdz ?

**Comment by cfstras** [comment]
@SimulatedGREG 
found a way to do this in my `main/index.js`:
```js
import installExtension, { REACT_DEVELOPER_TOOLS } from "electron-devtools-installer"
app.on('ready', () => {
  if (isDevelopment) {
      installExtension(REACT_DEVELOPER_TOOLS).catch(error => {
          console.log("Unable to install `react-devtools`: \n", error)
      })
  }
  mainWindow = createMainWindow()
})
```
although I have yet to find out where to put this to make the import conditional on development.
