### ISSUE TITLE
Modules not found error

### ISSUE THREAD

**Issue by nowyyz** [electron-userland/electron-webpack#120]
Basically it's the same issue as mentioned by @loopmode in https://github.com/electron-userland/electron-webpack/issues/104

When starting the application (`$ yarn run dev`) i get the error:
`Uncaught Error: Cannot find module 'source-map-support/source-map-support.js'`.
The same error appears for any other third-party package too. (In my case e.g. for 'vue-class-component').

It's even reproducible with the raw quickstart project:
- Clone Repo
- Run `$ yarn`
- Run `$ yarn run dev`

Im using yarn v1.5.1 with node v8.11.1 on Win10

**Comment by BobBuehler** [comment]
I am having the same issue. I have recreated it at work (Win7) and at home (Win10).

My developer tools are showing html

`require("module").globalPaths.push("C:\git\electron-webpack-quick-start\node_modules")`

when it should be

`require("module").globalPaths.push("C:\\git\\electron-webpack-quick-start\\node_modules")`.

Using the console to inspect `require("module").globalPaths` I see `"C:gitelectron-webpack-quick-start↵ode_modules"` as the second entry.

**Comment by BobBuehler** [comment]
I found a fix that works for me. I took the index.ejs posted [here](https://github.com/electron-userland/electron-webpack/issues/104#issuecomment-371056835) and moved the .replace call to inside the <%= %> tags.
```
require('module').globalPaths.push(
    '<%= htmlWebpackPlugin.options.nodeModules.replace(/\\/g, "\\\\") %>',
)
```

**Comment by BobBuehler** [comment]
Hoping for a built-in solution, I've created Issue #121.
