### ISSUE TITLE
Adding babel-preset-react causes errors on fresh clone

### ISSUE THREAD

**Issue by MikaAK** [electron-userland/electron-webpack#123]
If you freshly clone the seed and run `npm i -D babel-preset-react` and then start with `npm run dev` you get
```
 Module build failed: Error: [BABEL] ~/asdf/src/renderer/index.js: .env is not allowed in preset options```

**Comment by loopmode** [comment]
Weird. I just checked out my react quick start, installed and started and it works. Have a look.

https://github.com/loopmode/electron-webpack-quick-start

Using `"babel-preset-react": "^6.24.1"`

Actually I expected it to fail due to the webpack-sources problem that lingers around, but it just worked again.

**Comment by MikaAK** [comment]
I actually found out the cause. With latest babel you must install `@babel/preset-react` for any packages to work.

**Comment by loopmode** [comment]
Interesting that my `"babel-preset-react": "^6.24.1"` still works. Or works again.. I do remember it failing just a while ago. So, there still might be some potential environment side effects causing issues.
Anyways, we should confirm your find and update https://webpack.electron.build/add-ons#react-jsx

**Comment by bobringer** [comment]
@loopmode -- I can confirm that @MikaAK found my solution to the exact same issue.

**Comment by bmathews** [comment]
I had this issue too, but had to update configurators/js.ts to include `@babel/preset-`, e.g.:

```
addBabelItem(presets, configurator.getMatchingDevDependencies({
    includes: ["babel-preset-", "@babel/preset-"],
    excludes: ["babel-preset-env", "@babel/preset-env"]
  }));
```

**Comment by daviseford** [comment]
I am having this issue as well. @MikaAK's fix did not work for me, unfortunately.  I tried @bmathews solution as well and had no luck.

**Comment by tuxillator** [comment]
@loopmode your repo works for me but it's running `electron-webpack@1.12.1`, this is happening on for me on 2.0.1.

With 2.0.1 I'm having the same problem as the above and the workaround of installing `@babel/preset-react` along with the change to configurator/js.js doesn't work either.

**Comment by soederpop** [comment]
FYI with version 2.0.1 I have the following `.babelrc`

```
{
  "presets": [
    "@babel/react"
  ],
  "plugins": [
    "@babel/proposal-class-properties",
    "react-hot-loader/babel",
  ]
}
```

The babel-loader setup still uses the optimizations provided by `electron-webpack` and my project's customizations live in `.babelrc` -- they work together pretty nicely.

**Comment by akiver** [comment]
I opened a PR that fix #125 and it **may be** related to this issue.

I'm using `"@babel/preset-react": "7.0.0-beta.46"` with `"electron-webpack": "^2.1.0" (including the fix in the PR)` without problems.

.babelrc:
```
{
    "presets": [
        "@babel/preset-react"
    ]
}
```

Some parts of the docs are not up to date, do not use `babel-preset-react` with `electron-webpack 2.x`, it's using babel 7 and so you have to use `@babel/preset-react`

**Comment by hwkd** [comment]
I had the same problem, but once I added .babelrc to my project root directory with the following contents
`{
  "presets": [
    "@babel/preset-env",
    "@babel/preset-react"
  ]
}`
it worked out fine for me.

**Comment by loopmode** [comment]
The docs will suggest installing `@babel/preset-react` instead of `babel-preset-react`, see https://github.com/electron-userland/electron-webpack/commit/55a8942122d973e336442ec7e60137889300e82b
