### ISSUE TITLE
Native dependencies

### ISSUE THREAD

**Issue by andyfangdz** [electron-userland/electron-webpack#13]
Is there currently a good story for using native dependencies such as `sqlite3`?

[electron-rebuild](https://github.com/electron/electron-rebuild) is an excellent package for this, but it requires certain hacks when used with webpack, such as ``eval(`require("${packageName}")`)``, or explicitly editing webpack externals.

**Comment by develar** [comment]
If you use electron-builder, do not use electron-rebuild. electron-builder automatically rebuld native deps.

electron-webpack supports `.node` files using [node-loader](https://github.com/webpack-contrib/node-loader). 

```js
import node from 'file.node'
```

**Comment by develar** [comment]
> or explicitly editing webpack externals

By default all project dependencies listed as external modules. You don't need to think about. Handled for you.

**Comment by andyfangdz** [comment]
Oof, that's helpful. Is there an easy way of using `node-loader` to import a node addon in `node_modules`  without specifying the full path? Or maybe I should just use `bindings`...

**Comment by develar** [comment]
If you just use some native node module — just use it and do not think about it. I don't see any problem here — if module listed in the project `dependencies`, it is considered as external (if not whitelisted, no, no, your freedom is not restricted :)) and so, no problem.

**Comment by andyfangdz** [comment]
Ah thanks so much for the help!

**Comment by develar** [comment]
And if you use electron-builder, electron-builder will automatically detect `node` files and automatically unpacks it from ASAR.  We care about you :) Just develop your electron app :)
