### ISSUE TITLE
Conditional loading of css files based off environment variables not working

### ISSUE THREAD

**Issue by timganter** [electron-userland/electron-webpack#141]
Hello! I am using a UI framework that is conditionally loading .css files based off of environment variables that are set. Instead of loading only the .css files I want, ALL the .css files are being loaded. I must be doing something wrong. Halp!

The code from the UI framework has something like the following...

```javascript
if (process.env.SIZE_MEDIUM) {
  require('medium.css')
} else if (process.env.SIZE_LARGE) {
  require('large.css')
}
```

I am trying to set `process.env.SIZE_MEDIUM` to `true` so that only `medium.css` is loaded. However, both `medium.css` AND `large.css` are being loaded. This happens while running `dev`. 

Putting `console.log(process.env.SIZE_MEDIUM)` in the above conditional always outputs `undefined`. So, I must be doing something wrong.

I'm trying to set these environment variables in the following way.

```bash
# webpack.config.js

...
electronWebpack: {
  renderer: {
    webpackConfig: 'webpack.renderer.additions.js'
  }
}
```

```bash
# webpack.renderer.additions.js

const webpack = require('webpack')

module.exports = {
  plugins: [
    new webpack.DefinePlugin({
      'process.env.SIZE_MEDIUM': 'true'
    })
  ]
}
```

```bash
# from my package.json

  "main": "src/main/index.js",
  "scripts": {
    "dev": "electron-webpack dev",
    "build": "electron-webpack",
    "dist": "npm run build && electron-builder"
  },
  "dependencies": {
    "@babel/preset-react": "^7.0.0-beta.46",
    "install": "^0.11.0",
    "npm": "^6.0.0",
  },
  "devDependencies": {
    "babel-core": "^7.0.0-bridge.0",
    "babel-loader": "^7.1.4",
    "babel-polyfill": "^6.26.0",
    "babel-preset-env": "^1.6.1",
    "electron": "^1.8.6",
    "electron-builder": "^20.13.2",
    "electron-webpack": "^2.1.0",
    "webpack": "^4.8.1"
  }
```

Thanks all!
-Tim

**Comment by loopmode** [comment]
Hi.

The first file you mention, `webpack.config.js`, is basically just some random file that gets ignored :)
What's supported is either a `"electronWebpack"` key in package.json, or an `electron-webpack.json` file. 

See https://webpack.electron.build/configuration

**Comment by timganter** [comment]
Ah HA! Okay, cool. Thanks! I think that worked? I mean I get a different error now. I get this behavior now. https://github.com/electron-userland/electron-webpack/issues/125 

I'll close this for now and re-open if it's still an issue after I can get past https://github.com/electron-userland/electron-webpack/issues/125. 

Thanks again!
-Tim
