### ISSUE TITLE
Cannot resolve "vendor.js" from HTML loader plugin when using a vendor DLL

### ISSUE THREAD

**Issue by glek** [electron-userland/electron-webpack#155]
As the title says, I am unable to use the DLL feature. When I do I get the following error:

```
ERROR in ./dist/.renderer-index-template.html (./node_modules/html-loader/dist/cjs.js?minimize=false!./dist/.renderer-index-template.html)
      Module not found: Error: Can't resolve 'vendor.js' in '/data/repositories/gitlab/mdmulligan/electron/games/verhaal/dist'
       @ ./node_modules/html-loader/dist/cjs.js?minimize=false!./dist/.renderer-index-template.html 2:0-37 15:42-54
```

Version information:

* Electron 2.0.2
* electron-webpack 2.1.2
* webpack 4.10.2

I did find a similar issue (#15) in the issue tracker but that issue seems to have morphed to something slightly different.

After doing some research, I think I've tracked it down to an issues at [RendererTarget.ts:200](https://github.com/electron-userland/electron-webpack/blob/5ad2481e1b90f3c290d4fa63879b9620f88887de/packages/electron-webpack/src/targets/RendererTarget.ts#L200). The `html-loader-plugin` returned should be have the `url=false` parameter applied to it, otherwise Webpack tries to resolve the reference to the `vendor.js` file and fails because that file is in a sub-directory called `renderer-dll`.

**Comment by karanlyons** [comment]
I just hit this bug as well, and as glek said all that appears to be required is changing `!!html-loader?minimize=false!${filePath}` to `!!html-loader?minimize=false&url=false!${filePath}`.

Should we open a pull for this?

**Comment by mikestopcontinues** [comment]
Hey, can we get a merge on this?
