### ISSUE TITLE
Make it work with yarn workspaces, but without nohoist

### ISSUE THREAD

**Issue by amaurymartiny** [electron-userland/electron-webpack#164]
If I add the following config in my package.json, then `electron-webpack` works:

```
  "workspaces": {
    "packages": [
      "packages/*"
    ],
    "nohoist": [
      "**/electron-webpack",
      "**/electron-webpack/**"
    ]
  },
  "engines": {
    "yarn": "^1.4.2"
  },
```

However, it would be nice to have `electron-webpack` work without nohoist.

**Comment by loopmode** [comment]
The nohoist option is your final escape hatch when you have have multiple packages in a yarn workspace that depend on some package in different versions. In this case, it seems to be some sub-dependency, e.g. maybe `webpack` itself.
This is entirely related to how yarn workspaces and its dependency hoisting work. And to the specific setup of any particular project using a yarn workspace.

In short: I don't think there is anything we could do "inside" `electron-webpack` about this.
