### ISSUE TITLE
Cannot find name '__static'.

### ISSUE THREAD

**Issue by gpalomar** [electron-userland/electron-webpack#168]
__static variable is not found in my main/index.ts when runnin `electron-webpack dev`.
I'm using this versions:
`"electron-webpack": "^2.1.2"
"electron-webpack-ts": "^2.0.2"`

What i'm doing wrong?
Thanks!

**Comment by hoythan** [comment]
look this.
https://github.com/electron-userland/electron-webpack/issues/172#event-1724860963
