### ISSUE TITLE
using plugins in combination with vue-class-component or vue-property-decorator in typescript

### ISSUE THREAD

**Issue by rharink** [electron-userland/electron-webpack#170]
I'm using the electron-webpack in combination with Vue and Typescript. Everything works fine until I want to use plugins like vue-router, vuex, or any other for that matter.

the problem occurs when using `@Component` in a  Vue single file component like so:
```
<template>
  <div>
    <h2>Hello world {{$route}}</h2>
  </div>
</template>

<script lang="ts">
import Vue from "vue"
import { Component } from "vue-property-decorator"

@Component
export default class Home extends Vue {
  created() {
    console.log(this.$router)
  }
}
</script>
```
The value of `this.$router` is undefined. When you leave out the`@Component` everything works as expected. A workaround would be to use `$root.$router`.  

Where should I start looking to solve this problem? Thanks! 

My `package.json` dependencies:
```
{
  "dependencies": {
    "source-map-support": "^0.5.5",
    "vue-class-component": "^6.2.0",
    "vue-property-decorator": "^7.0.0",
    "vue-router": "^3.0.1",
    "vuex": "^3.0.1"
  },
  "devDependencies": {
    "css-loader": "^0.28.11",
    "electron": "2.0.0",
    "electron-builder": "^20.11.1",
    "electron-webpack": "^2.1.0",
    "electron-webpack-ts": "^2.0.2",
    "electron-webpack-vue": "^2.1.3",
    "node-sass": "^4.9.0",
    "sass-loader": "^7.0.3",
    "tslint": "^5.10.0",
    "typescript": "^2.9.2",
    "vue": "^2.5.16",
    "webpack": "^4.8.1"
  },
  "resolutions": {
    "webpack-sources": "1.0.1"
  }
}
```

**Comment by michaeljpeake** [comment]
Did you find any solution to this? I've just spent a day going round in circles with a similar issue, trying to access `this.$store`. Works fine if you don't use `@Component`.

**Comment by aritsune** [comment]
ran into this as well, any ideas?

**Comment by rharink** [comment]
We moved to React, never solved the problem though. Sorry,😅
