### ISSUE TITLE
html-loader support

### ISSUE THREAD

**Issue by develar** [electron-userland/electron-webpack#19]
https://electron-builder.slack.com/archives/C3X4YCA14/p1504853880000076?thread_ts=1504770211.000387&cid=C3X4YCA14

> i'm using angular 1.5 and i need the ability to load in html templates as string via es6 import

`import html from './myfile.html';`

**Comment by jdsmith2816** [comment]
If you wanted to provide more natural angular 1.5 support then additionally a moduleName parameter that would turn the current

```<div id="app"></div>``` 

into

```<div ng-app="providedAppNameHere"></div>```

would go a long way.  

The current index.html is actually usable but the developer needs to know to utilize angular's bootstrap method instead which isn't the typical path.

```angular.element(document).ready(function() { angular.bootstrap(document.getElementById('app'), ['providedAppNameHere']);});```

**Comment by SimulatedGREG** [comment]
Maybe we could conditionally render `<div ng-app="app-name"></div>` based on the presence of `angular` being installed as a dependency? I'm not sure if that differs on how Angular 2/4 is handled though.

**Comment by abruneau** [comment]
Do you know an example of electron-webpack with Typescript and Angular4 ?

**Comment by darrenmothersele** [comment]
@abruneau check the linked issue for my attempt at using Angular 4: https://github.com/electron-userland/electron-webpack/issues/22
