### ISSUE TITLE
Production builds are broken if I don't put an `eval ( '' )` in my code

### ISSUE THREAD

**Issue by fabiospampinato** [electron-userland/electron-webpack#196]
I've written a [note taking app](https://github.com/fabiospampinato/noty/tree/06ab0a8d712919a6e199fb8a5f18bda56b1b20f8) using this framework, and I've stumbled on a super weird bug: everything works fine during development, but when I build the app for production (`npm run build:mac` and open `releases/mac/Noty.app`) the textarea/editor of the app loses focus as soon as something is typed, so it's unusable.

At first I thought there was a bug in my code, but then I found the "fix": 

1. I wanted to put a `debugger` statement in the `render` method of my React app in order to check what was going on, but that didn't work on the production build, maybe it got stripped out, makes sense
2. I put an `eval ( 'debugger' )` there instead, and that worked, but now the bug doesn't manifest itself
3. Just putting an `eval ( '' )` [here](https://github.com/fabiospampinato/noty/blob/06ab0a8d712919a6e199fb8a5f18bda56b1b20f8/src/renderer/components/app.tsx#L283) fixes the problem

My guess is that in your build toolchain there's some tool making a stupid optimization of that render method or something, which it can't do in the presence of an `eval` call because it's not sure if that optimization is safe to make. Just a guess.

Could you please take a look at this? I've wasted a bit of sanity trying to debug this, and the "fix" I found for it is super ugly.

**Comment by fabiospampinato** [comment]
This was actually a problem of the minifier, for specifically the `keep_fnames` option, which is set to `false` by default.

Maybe the default configuration should be safer than that.

**Comment by loopmode** [comment]
I agree that we should set `keep_fnames` to `true`. 
We don't need to save bandwidth by mangling names, and obfuscating code for "protective measures" shouldn't be the scope here..

**Comment by loopmode** [comment]
Enable `keep_fnames`: https://github.com/electron-userland/electron-webpack/pull/304
