### ISSUE TITLE
Build error caused by dll in 1.5.0

### ISSUE THREAD

**Issue by FantasticFiasco** [electron-userland/electron-webpack#20]
I'm using the dll feature and when trying to upgrade to 1.5.0 the build fails.

The build log can be seen [here](https://travis-ci.org/FantasticFiasco/axis-searchlight/builds/273587646) and the `electronWebpack` configuration in `package.json` can be seen [here](https://github.com/FantasticFiasco/axis-searchlight/blob/greenkeeper/electron-webpack-1.5.0/package.json).

**Comment by develar** [comment]
I will fix in 2 weeks (vacation :))

**Comment by FantasticFiasco** [comment]
No problem! Keep working on that tan :-)
