### ISSUE TITLE
__static in Production

### ISSUE THREAD

**Issue by benjaminadk** [electron-userland/electron-webpack#205]
I am having trouble with the `__static` directory in production.  It is working fine in development and I am using version 2.3.1.  I am having trouble making sense of the other issues around this problem.

Path in dev: `C:\Users\Benjamin\Desktop\project\electron-picker-2\static\picker-icon.ico`

Path in prod: `C:\Users\Benjamin\Desktop\project\electron-picker-2\node_modules\electron\dist\resources\static\picker-icon.ico`

This example is an icon and my app relies on json files in `__static` as well.  Not sure what the best approach is to resolve this.

**Comment by loopmode** [comment]
Fixed with https://github.com/electron-userland/electron-webpack/commit/6188f0879a6345adf91f95fe2a6398bc32c26e3d
