### ISSUE TITLE
Question: How to use newer UglifyJsPlugin, i.e. Run webpack without -p switch

### ISSUE THREAD

**Issue by novaterata** [electron-userland/electron-webpack#222]
I'm taking over an electron-webpack project and I'm stuck on 1.13.0 until I can figure out how to migrate a bunch of babel6 junk to babel7. The version of uglify-js bundled with webpack 3.x is too old to handle es6. This can be worked around with webpack by upgrading the UglifyJsPlugin, adding it explicitly, and calling webpack CLI without the production -p switch; however, I don't see an obvious way to do this with electron-webpack. Is there anyway to accomplish the same goal with electron-webpack?

**Comment by develar** [comment]
electron-webpack doesn't use uglify-js because of that. Instead, since 2.4.0, 

> use terser-webpack-plugin because uglifyjs-webpack-plugin doesn't support ES6+ anymore

So, you don't need to worry about it at all.

**Comment by novaterata** [comment]
@develar I don't think I can upgrade to 2.x because I can't upgrade to babel7, and webpack 4 yet

**Comment by novaterata** [comment]
I think I figured it out, by passing in --env.production=false while NODE_ENV=production I can do the same as webpack without -p switch
