### ISSUE TITLE
WatchFilterPlugin configuration

### ISSUE THREAD

**Issue by r4zzz4k** [electron-userland/electron-webpack#23]
I'm looking through code which generates configurations and accidentally noticed that there is an array called `watchIgnore` which is populated, but never used for anything instead of logging. There might be an issue here.
https://github.com/electron-userland/electron-webpack/blob/daafee6ad2ea27a64833278f2001739a99012827/packages/electron-webpack/src/targets/BaseTarget.ts#L111-L141

**Comment by develar** [comment]
Thanks, I will remove dead code. We use special WatchFilterPlugin to ignore.
