### ISSUE TITLE
IPC communication fails silently for electron-redux between renderer & main thread

### ISSUE THREAD

**Issue by walleXD** [electron-userland/electron-webpack#24]
Hi,

I had used electron-redux with electron-forge and everything works very well but while using it with electron-webpack, the renderer fails to communicate with the main thread using IPC. I tried out the exact same setup that I had with electron-forge but it still doesn't work. I think it's something specific to electron-webpack as the main thread is successfully in communicating with the renderer but the opposite fails. 

I have also opened an issue in the electron-redux repo [hardchor/electron-redux/#63](https://github.com/hardchor/electron-redux/issues/63).

Any ideas on what can cause such issue?

**Comment by develar** [comment]
I will check 21 September.

**Comment by walleXD** [comment]
@develar it seems to be a restriction related how electron-redux handles action types. Thanks for the awesome library and also taking the time to respond!
