### ISSUE TITLE
__static doesn't work for images in development

### ISSUE THREAD

**Issue by cmeeren** [electron-userland/electron-webpack#241]
How are we supposed to use simple images?

I'm trying to add a simple `<img src="..."` to my app. I have placed `myimg.png` in the `static` folder. When I set the image source to simply `myimg.png`, everything works in dev mode, but the image does not show up in production (presumably since it's in a `resources` subfolder).

On the other hand, if I prefix the filename with `__static`, it works in production mode, but in debug mode I get the following error in Chrome DevTools:

`Not allowed to load local resource: file:///<repo folder>/static/myimg.png`

(Related to #99, but not the same, since I'm wondering in general how one should use simple images.)

**Comment by cmeeren** [comment]
Sorry to bump this. This seems like it should be a simple and normal thing do to, but I'm completely lost and have no idea how to reliably show images in my app across dev/production environments. What's the correct way to do this?

**Comment by loopmode** [comment]
There are multiple correct ways.. Here is one that I recommend.
Read more about it in https://github.com/electron-userland/electron-webpack/issues/99

The trick is to have a utility function that gives you a different URL for an asset in development and in production. Then, whenever you need to use a static image (or any other asset), use that function to get the actual URL at runtime.

1) Prepare the utility, for example:

```jsx
// src/renderer/static.js

import path from 'path'
import * as url from 'url'

const isDevelopment = process.env.NODE_ENV !== 'production'

// see https://github.com/electron-userland/electron-webpack/issues/99#issuecomment-459251702
export function getStatic(val) {
  if (isDevelopment) {
    return url.resolve(window.location.origin, val)
  }
  return path.resolve(__static, val)
}
```


2) Use it anywhere your app, e.g:

```jsx
// src/renderer/App.js
import React from 'react'
import { getStatic } from '@/static'

function App() {
  return (
    <div className="App">
        <img src={getStatic('electron.png')} />
    </div>
  )
}
```

Here is [an example](https://github.com/loopmode/electron-webpack-quick-start/blob/react/src/renderer/App.js) that embeds an image twice: once using `require`, and once using the static folder and the described method. This is the outcome, the screenshot is from the installed production app.

![image](https://user-images.githubusercontent.com/623225/56029841-a4afde00-5d1b-11e9-95c1-2fdc12848c0e.png)

Closing for now. We can re-open if necessary.

**Comment by cmeeren** [comment]
This is basically what I ended up doing. :)

It would be great if `getStatic` was part of electron-webpack! Could you consider adding it?

**Comment by cmeeren** [comment]
Note that the current docs are misleading. They say:

> `__static` is made available to provide you a path to your `static/` folder. This variable is available in both `development` and `production`.

And then:

> ```js
> /* use `path` to create the full path to our asset */
> const pathToAsset = path.join(__static, '/foobar.txt')
> ```

This will only work if setting `WebPreferences.webSecurity` to `false`, which is not recommended. The `getStatic` solution above avoids this. The docs should either mention that `webSecurity` must be disabled, or present the `getStatic` solution.

Note by the way that the `getStatic` solution seems to cause a delay in asset loading on `development`.

**Comment by dospolov** [comment]
I've got opposite issue: dev worked fine, production doesn't.

These 3 steps helped:
1. create static.js helper: 
```
import path from 'path'
import * as url from 'url'

// see https://github.com/electron-userland/electron-webpack/issues/99#issuecomment-459251702
export function getStatic(val) {
  if (process.env.NODE_ENV !== 'production') {
    return url.resolve(window.location.origin, val)
  }
  return path.resolve(__static, val)
}
```
2. use it:
```
<img src={getStatic('./as-default.png')} alt="" />
```

3. update build configuration in `package.json`:
```
"extraResources": [
      {
        "from": "./static",
        "to": "static"
      },
]
```

**Comment by loopmode** [comment]
Here is an example repo based on current electron-webpack-quick-start (time of writing):
https://github.com/loopmode/electron-webpack-static-examples
