### ISSUE TITLE
Hot Module Replacement works only on port 9080

### ISSUE THREAD

**Issue by AndreyWeber** [electron-userland/electron-webpack#25]
```javascript
const mainWindow = new BrowserWindow();
let url = isDevelopment
    ? 'http://localhost:9080' // <-- Code won't work in case of value other than 9080
    : `file://${__dirname}/index.html`;
win.loadURL(url);
```

In case, if I specify port number other than 9080, HMR won't work and renderer process won't start, because port value 9080 hardcoded in 'packages/electron-webpack/src/targets/RendererTarget.ts'. No notification will appear, documentation doesn't contain anything about that:

```javascript
configurator.config.devServer = {
        contentBase,
        port: 9080,
        hot: true,
        overlay: true,
      }
```

**Comment by loopmode** [comment]
This is not just a HMR issue. It makes it impossible to work on two applications at the same time (e.g. I intended to work on a client app and a separate "editor" app that can manipulate content)
