### ISSUE TITLE
Unit tests

### ISSUE THREAD

**Issue by FantasticFiasco** [electron-userland/electron-webpack#26]
I've noticed that there is some kind of support for tests, because of `node_modules/electron-webpack/webpack.test.config.js`, but it does not seem to be fully functional, nor documented.

Where are we on tests, is that something that will be supported in the future, or should one be able to write unit tests without the help of `electron-webpack`?

**Comment by hetsch** [comment]
I'm too quite stuck how to implement unittesting. It would be awesome if you provide us some hints or examples how to invoke the unittest with webpack.test.config.js and what directory structure that it might require. Nevertheless, thank's for the awesome project.

**Comment by FantasticFiasco** [comment]
No, I've continued to implement without unit tests. Hopefully I will get back to writing unit tests some day.

**Comment by hetsch** [comment]
@develar or @SimulatedGREG. Sorry for pushing this, but I've seen in the commits that both of you seem to be the main contributers here. I had a look at the source code and found some preparations for testing purposes, what makes me think that one day you considered this case. It would be really helpful if you could give us some ideas on how it might be possible to integrate and bootstrap unittests? This package really worked well for me and working testi environment would be the sugar on top.

**Comment by loopmode** [comment]
It really depends what you actually want to test. I doubt that the test setup inside the electron-webpack source will be provided to us "consumers" of it, who use it as a "compiled" library. My bet is it will probably stay behind the scenes forever, as it should be customized to just test the functionality electron-webpack provides, not what we users do with it. 
I haven't set up testing for the actual DOM in my project, but for actual unit tests (modules that provide pure functions) I was able to quickly punch together a setup using `tape` and `babel-tape-runner` just as I would have done in any other node project.

**Comment by hetsch** [comment]
@loopmode thank you very much for your thoughts. My concerns were about testing the DOM, but I think these concerns were more related to my missing knowledge in setting these up in javascript projects. I will give tape a try. Thank's for your help!

**Comment by loopmode** [comment]
@hetsch you're welcome! In case it wasn't clear: Tape does not provide DOM testing out-of-the-box, but it's very easy to set up for non-DOM tests. I actually just put something so simple on github that it's a good example: https://github.com/xailabs/utils-obj

just have a look at the package.json, tests.js, and the actual test file in src/ObjUtil.test.js. I just copied this out of an actual electron-webpack project that uses exactly the same testing setup.

**Comment by FantasticFiasco** [comment]
Thanks for all this information! I consider this issue closed.
