### ISSUE TITLE
use babel-plugin-import with electron-webpack error

### ISSUE THREAD

**Issue by r4ggj** [electron-userland/electron-webpack#263]
I use electron-webpack.when I add a UI Library "antd",and this library require "babel-plugin-import".I installed it,but can not run. I don't known what's wrong!!

**Comment by UXDart** [comment]
I have the same problem, just adding "babel-plugin-import" gives an exception... somewhere there is an "import" used... any ideas?

**Comment by loopmode** [comment]
Two hints:
- you must add to `devDependencies`
- the plugin must be compatible with Babel 7, e.g. if there is a `@babel/*` version of it, use that one

**Comment by loopmode** [comment]
Well there is one thing you can do out of the box - in package.json, put it into regular dependencies instead of devDependencies :)

**Comment by loopmode** [comment]
Ahr! I accidentally replaced my previous comment instead of posting a new one..damn cellphone must have tricked me..
See https://github.com/electron-userland/electron-webpack/issues/263#issuecomment-490520272

**Comment by loopmode** [comment]
Something is weird. My comments do not get added but instead they seem to be replacing my previous comment for buggy reasons. Might be just a bug on my phone..
@UXDart just add it to regular dependencies instead of devDependencies, and it is not automatically used by electron-webpack

**Comment by loopmode** [comment]
haha. there seems to be some kind of date-related bug on github.

![image](https://user-images.githubusercontent.com/623225/57388440-74434e80-71b8-11e9-85f5-2e85044869d8.png)

**Comment by UXDart** [comment]
thanks! that works! 👍
