### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by 9ae8sdf76** [electron-userland/electron-webpack#267]
The last update was 24 days ago, and apparently the update was considered a measly "chore". There are a lot of people with a lot of valid issues, and it doesn't appear that the devs care enough to even tell them to bugger off. Am I wrong? 

I feel like I've wasted a lot of days trying to get this supposedly easy and non-impeding package to work, just to realize that I have nowhere to turn for questions.

> Because setting up webpack in the electron environment shouldn't be difficult.

And yet here we are...

**Comment by develar** [comment]
Low maintenance mode ;) And for now I don't see questions from you. Anyway, project is driven by users, as you can see, latest releases contains quite a lot pull requests.
