### ISSUE TITLE
Base `tsconfig` breaks Mocha with ES6

### ISSUE THREAD

**Issue by rreed** [electron-userland/electron-webpack#277]
For the fast version, I've provided an MCVE here: https://github.com/rreed/electron-webpack-mcve

Basically, a single test that imports an es6 module (`import * as Foo from '../src/foo';`) fails with `SyntaxError: Unexpected token *` reliably. This is ONLY true when including the electron-webpack base config via `"extends": "./node_modules/electron-webpack/tsconfig-base.json"
`; changing the files to vanilla JS makes them work again, and deletiing `tsconfig.json` entirely makes them work again.

Unfortunately, "just delete tsconfig" is not a real option, because it makes React terribly sad. So what's up here?

**Comment by lookapanda** [comment]
It's because `electron-webpack` comes with it's own tsconfig file and it has set `module: "esnext"` which is incompatible. Unfortunately, this makes it impossible for me to use `electron-webpack` :(

**Comment by rreed** [comment]
That's fine! This was over a year ago, the project I needed this for is long, long gone. :)

Thanks for this software though!

**Comment by loopmode** [comment]
But normally, you extend the tsconfig provided by electron-webpack - can't you just override the setting?

**Comment by ejohnso49** [comment]
For anyone intested, you should be able to override via a `tsconfig.json` file in your project root. Example contents:
```
{
    "extends": "./node_modules/electron-webpack/tsconfig-base.json",
    "compilerOptions": {
        "module": "CommonJS",
        "alwaysStrict": true
    }
}
```
