### ISSUE TITLE
Host vuejs In a separate server

### ISSUE THREAD

**Issue by supertiger1234** [electron-userland/electron-webpack#281]
Is there anyway to host the vuejs server in a separate server? I want to make a website and electron app. I want to check if the client is electron, use features like remote, if not, don't use them features

Thanks.

**Comment by loopmode** [comment]
I suggest using a yarn workspace with multiple packages, e.g. one being the "core", one the web app and one the electron app.
Using a yarn workspace, the packages are symlinked and you can simply import/require them as needed.
The web app can be whatever setup you prefer.
Then, you could set something like `process.env.APP_ENV = 'electron'` or 'web' in your entry files, before doing any imports.
In your "core" components that get imported, you can check for the env setting and branch your code further, as needed.
Webpack with uglify plugin will drop the unwanted code branches at build-time and only follow the "good path" respecting your env setting.

**Comment by supertiger1234** [comment]
i managed to fix it without using electron-webpack. i just had to use `const electron = window.require("electron");` instead.
