### ISSUE TITLE
Renderer Window Shortcuts don't work

### ISSUE THREAD

**Issue by Heroyoulook** [electron-userland/electron-webpack#282]
Am I the only one with this issue?

I even tried it with the electron-webpack-quick-start.

Example hitting F11 doesn't full screen.

Clicking on the actual menu item works though.

**Comment by loopmode** [comment]
Indeed, it doesn't work. When I hit that problem, I worked around it because I couldn't understand and properly fixed it.

So, for reference, here's the workaround:

- In your renderer process, you register manual key handling
- Use IPC to communicate between renderer and main process
- When you detect the key in your renderer process, send a message to the main process which can make the window enter or exit fullscreen mode

In `src/renderer/index.js`
```
const { ipcRenderer } = require("electron");
document.addEventListener("keydown", function(event) {
  switch (event.keyCode) {
    case 27: // Escape
      ipcRenderer.send("exit-fullscreen");
      break;
    case 70: // F
      if (event.ctrlKey) {
        ipcRenderer.send("toggle-fullscreen");
      }
      break;
  }
});
```

In `src/main/index.js`:
```

const { ipcMain } = require("electron");
ipcMain.on("enter-fullscreen", () => {
  if (!mainWindow.isFullScreen()) {
    mainWindow.setFullScreen(true);
    mainWindow.setMenuBarVisibility(false);
  }
});
ipcMain.on("exit-fullscreen", () => {
  if (mainWindow.isFullScreen()) {
    mainWindow.setFullScreen(false);
    mainWindow.setMenuBarVisibility(true);
  }
});
ipcMain.on("toggle-fullscreen", () => {
  const nextFullscreen = !mainWindow.isFullScreen();
  mainWindow.setFullScreen(nextFullscreen);
  mainWindow.setMenuBarVisibility(!nextFullscreen);
});
```

**Comment by loopmode** [comment]
Please note also that if you need cross-platform support, `event.ctrlKey` might only work for Windows and Linux users, but not for Mac users.

As the official [electron docs on this topic](https://electronjs.org/docs/tutorial/keyboard-shortcuts) suggest, you could use a library like [Mousetrap](https://www.npmjs.com/package/mousetrap) and instead define something like:

```
Mousetrap.bind(['command+f', 'ctrl+f'], function() {
    ipcRenderer.send("toggle-fullscreen");
    return false;
});
```

**Comment by Heroyoulook** [comment]
Great work around thank you.  Was going out of my mind trying to reverse engineer the repo to determine the cause of the globalshortcuts not working.
Small price to pay for the ease of use of this.

**Comment by loopmode** [comment]
Glad to hear! Maybe some day we'll figure out why shortcuts don't work in the first place.
My gut says it has to do with DLLs or some other webpack feature we use that somehow puts main and renderer farther apart from each other than anticipated by the electron engineers..
