### ISSUE TITLE
HMR not working - a detail missing in docs?

### ISSUE THREAD

**Issue by loopmode** [electron-userland/electron-webpack#29]
Hi. For me HMR doesn't work out of the box.
I have to manually accept and rerender like this:

```
// renderer/index.js
import React from 'react';
import ReactDOM from 'react-dom';
import App from './App';

const rootEl = document.getElementById('app');

ReactDOM.render(<App />, rootEl);
if (module.hot) {
    module.hot.accept('./App', () => {
        const NextApp = require('./App').default;
        ReactDOM.render(<NextApp />, rootEl);
    });
}
```
When I have the manual `if (module.hot) ... accept` in place, it works just fine. (for JS files)

If I don't do it, I get a full page reload with this output in the browser console:

```
[WDS] App hot update...
[HMR] Checking for updates on the server...
[HMR] Cannot apply update. Need to do a full reload!
module.exports @ log.js:25
(anonymous) @ dev-server.js:34
log.js?4244:25 [HMR] Error: Aborted because ./src/renderer/App.js is not accepted
Update propagation: ./src/renderer/App.js -> ./src/renderer/index.js -> 0
    at hotApply (http://localhost:9080/renderer.js:441:30)
    at http://localhost:9080/renderer.js:290:21
    at <anonymous>
module.exports @ log.js:25
(anonymous) @ dev-server.js:35
Navigated to http://localhost:9080/
```

Is something is wrong with my setup, or is the `if (module.hot) ...accept...` detail just missing from the documentation?
I did modify the setup to accept stage-0 and legacy-decorators (see https://github.com/electron-userland/electron-webpack/pull/28) but I don't think it should matter in this context.

**Comment by SimulatedGREG** [comment]
There currently isn't full *first-class* support for `react`, so it would seem HMR needs a few more plugins. Will be looking into.

**Comment by loopmode** [comment]
Well it might be good enough to just add the snippet above with an additional comment to the docs. Will see if I can suggest something via PR.

**Comment by SimulatedGREG** [comment]
Looking into using https://github.com/gaearon/react-hot-loader

**Comment by loopmode** [comment]
I tried it earlier today. In fact, it basically requires the same `if (module.hot)` code mentioned above, so I removed it from my project again as I didn't see any benefit.
Of course if it helps simplify things internally, it might be worth it. 
But: your project here is basically awesome as it is. Simply adding the snippet - plus my PR that was merged into 1.6.0 earlier today - gives 100% HMR and a great workflow and dev experience.

**Comment by walleXD** [comment]
@loopmode react hot reload works perfectly for me. Here's my main render function:
```es6
const renderApp = Component => render(
  <AppContainer>
    <ReduxProvider store={store}>
      <Router history={history}>
        <RebassProvider>
          <Component />
        </RebassProvider>
      </Router>
    </ReduxProvider>
  </AppContainer>,
  document.getElementById('app')
)

renderApp(App)

if (module.hot) module.hot.accept('./containers/App', () => renderApp(App))
```

**Comment by loopmode** [comment]
@walleXD Sure, works fine for me too - with any variation of `if (module.hot) module.hot.accept('./containers/App', () => renderApp(App))`.

My point is that we should mention that in the docs somewhere.
(It's not 100% "normal" to have that - I have several webpack setups with HMR that do not need that)
