### ISSUE TITLE
on development systemPreferences.isDarkMode() is always false

### ISSUE THREAD

**Issue by UXDart** [electron-userland/electron-webpack#298]
I'm using Electron 5.0.6, and now systemPreferences.isDarkMode() returns false when main/index is executed "during development". (on production it works ok). is this a problem with electron-webpack or something else? (I'm on OSX with dark mode enabled)

also I fixed manually if in development, the app data folder is the wrong one... (found some issues about this on the issues on this repo, but no solution)

again, not sure if this problems are really from this repo or not. maybe someone knows better... but no one is reporting this problem on Electron repo (dark mode at least)... TIA

**Comment by loopmode** [comment]
Hi. Actually, there was an issue in the electron repo that looks related. It was created 4 days ago, fixed and merged for release in 6.0.0-beta.11 yesterday:

https://github.com/electron/electron/pull/18949

Might be it, or? I'm not on Mac do I can't try out anything..

**Comment by UXDart** [comment]
I see... I thought that was only for OSX Catalina, but checking the code changes, is not.... Thx!
