### ISSUE TITLE
HMR for stylesheets

### ISSUE THREAD

**Issue by loopmode** [electron-userland/electron-webpack#30]
Currently, `ExtractTextPlugin` is used for stylesheets in development mode, and HMR does not work. You need to manually reload the page.

However, there is a really simple fix for this, using `css-hot-loader` in combination. See https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/384#issuecomment-300723389

It's a pretty much non-critical change and a big win for developers.
Of course it should only be applied when in development, not when publishing dist.

I wanted to add a separate pull request, but I'm still a bloody noob in terms of github pull requests.
So, unfortunately this addition landed in the same PR I had already created: https://github.com/electron-userland/electron-webpack/pull/28

**Comment by loopmode** [comment]
Untill the PR is merged (or not..?) I use a pretty naive but effective patching mechanism to have these features. In case somebody is interested, see here:

https://github.com/loopmode/electron-webpack-quick-start/blob/master/package.json#L6
https://github.com/loopmode/electron-webpack-quick-start/tree/master/scripts

On postinstall, I perform a simple text replace on the actual code of `electron-webpack` and patch the missing features into it. Very ugly, but works fine for now.

**Comment by walleXD** [comment]
Tbh the best possible solution atm would be to work on a solution to expose the Webpack configs so that we are also able to use the cli features similar to how [`razzle`](https://github.com/jaredpalmer/razzle#extending-webpack) & [`backpack.js`](https://github.com/jaredpalmer/backpack#how-to-use) loads user configs from a designated file, similar to Webpack

**Comment by loopmode** [comment]
Actually, my PR got merged in version 1.6.0 and it works nicely. Just use `yarn add electron-webpack@1.6.0`  - it's a pre-release as of now.
I guess we should close this issue.
