### ISSUE TITLE
Having an dependency using 'export' breaks at app startup

### ISSUE THREAD

**Issue by fstephany** [electron-userland/electron-webpack#301]
Here's my package.json:

```json
{
  "name": "electron-webpack-quick-start",
  "version": "0.0.0",
  "license": "MIT",
  "esm": "auto",
  "scripts": {
    "dev": "electron-webpack dev",
    "compile": "electron-webpack",
    "dist": "yarn compile && electron-builder",
    "dist:dir": "yarn dist --dir -c.compression=store -c.mac.identity=null"
  },
  "dependencies": {
    "source-map-support": "^0.5.12",
    "esm": "^3.2.25",
    "@atlaskit/navigation-next": "6.3.0"
  },
  "devDependencies": {
    "electron": "5.0.4",
    "electron-builder": "^20.44.4",
    "electron-webpack": "^2.7.1",
    "webpack": "~4.35.0"
  } 
}
```
And my src/renderer/index.js:

```
import { LayoutManager } from "@atlaskit/navigation-next";

let app = document.getElementById("app");
let layoutManager = LayoutManager;
console.log(app);
console.log(layoutManager);
```

The error seems to appear as soon as the external dependency is loaded. Here's the error message in the electron console (renderer side) 

```
Uncaught /home/fstephany/Code/Play/new-electron-webpack-project/node_modules/@atlaskit/navigation-next/index.js:2
export { default as ContainerHeader } from './components/presentational/ContainerHeader';
^^^^^^

SyntaxError: Unexpected token export
    at new Script (vm.js:85:7)
    at createScript (vm.js:266:10)
    at Object.runInThisContext (vm.js:314:10)
    at Module._compile (internal/modules/cjs/loader.js:742:26)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:820:10)
    at Module.load (internal/modules/cjs/loader.js:677:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:609:12)
    at Function.Module._load (internal/modules/cjs/loader.js:601:3)
    at Module.require (internal/modules/cjs/loader.js:715:19)
    at require (internal/modules/cjs/helpers.js:14:16)
```

This seems to indicate that `export` is not available. My gut feeling tells me that I need to configure something with Babel to get it available but I can't find what. Any hint on how to fix/debug this? 

A repo with the minimal project to reproduce is available:  [fstephany/bug-report-electron-webpack](https://github.com/fstephany/bug-report-electron-webpack).

**Comment by fstephany** [comment]
Mmm. When digging into this it is quite surprising that this code is executed by Node (`vm.js`) as it should only be processed by webpack and fed into the Electron renderer. Or am I missing something?

**Comment by fstephany** [comment]
It looks really close to [this issue on StackOverflow](https://stackoverflow.com/questions/55690581/export-default-not-supported-in-react-app). 

It might be the `export { default as ...` from the dependency that is not understood. I don't know where to look to solve this.

**Comment by fstephany** [comment]
I got it to work by putting the atlaskit dependency in the whiteListedModules list:

```
  "electronWebpack": {
    "whiteListedModules": ["@atlaskit/navigation-next"]
  },
```

**Comment by loopmode** [comment]
@fstephany glad you figured it out! Sorry for no response :)
I almost replied with something about Babel plugins in the morning - I'm happy I didn't as it would have been misleading..
