### ISSUE TITLE
Dev mode doesn't work with Electron v6.0.0

### ISSUE THREAD

**Issue by cmeeren** [electron-userland/electron-webpack#308]
Latest electron-webpack doesn't work with Electron v6.0.0 (specifically, it works with v6.0.0-beta.13, but not 6.0.0-beta.14, 6.0.0-beta.15, the final 6.0.0 release, or 7.0.0-beta).

Repro: Clone [electron-webpack-quick-start](https://github.com/electron-userland/electron-webpack-quick-start), upgrade all packages with `yarn upgrade --latest`, and run `yarn dev`. No electron window opens. (The window opens successfully using when electron 6.0.0-beta.13 and below.)

**Comment by cmeeren** [comment]
Can I just get a confirmation that this is indeed a bug with electron-webpack? Seems to be fairly critical since dev mode simply doesn't start. (For all I know it might be fixed with some config, but then the electron-webpack-quick-start repo should be updated accordingly.)

**Comment by cmeeren** [comment]
Actually, it seems like it's an Electron bug: https://github.com/electron/electron/issues/19468

**Comment by caesar** [comment]
It's an Electron bug but fixing it isn't a priority for the Electron team, so projects using devtools extensions will want to either disable them before upgrading or make a note to avoid dark mode on Windows.
