### ISSUE TITLE
`electron-webpack dev` not works with native modules such `sqlite3` - Possible patch for a solution

### ISSUE THREAD

**Issue by ozelot379** [electron-userland/electron-webpack#310]
* **Version**: (I am not using `electron-builder`, but I use `electron-packager` v14.0.4, but this is inrevelant, since the issue is in `electron-webpack dev`)

I am not using `electron-updater`

* **Target**: `electron-webpack dev`

I am using the `sqlite3` module in an electron application, using `electron-webpack`

Because it's a native nodejs module, I need to exlucde it from webpack (and so still include it in `node_modules` for packaging)
```
externals: [
		/^sqlite3$/
	],
```

I run `electron-rebuild` for develop (`postinstall` script) and also for packaging with `electron-packager`
```
afterCopy: [(buildPath, electronVersion, platform, arch, callback) => {
			electronRebuild.rebuild({buildPath, electronVersion, arch}).then(() => {
				callback();
			}).catch((error) => {
				callback(error);
			});
		}]
```
For packaging it work perfectly, but if I run the develop with `electron-webpack dev`, I get the follow error
```
Uncaught Error: Cannot find module 'sqlite3'
```

I can fix it with the follow patch for me
```
diff --git a/node_modules/electron-webpack/out/dev/dev-runner.js b/node_modules/electron-webpack/out/dev/dev-runner.js
index 285f712..e8a9539
--- a/node_modules/electron-webpack/out/dev/dev-runner.js
+++ b/node_modules/electron-webpack/out/dev/dev-runner.js
@@ -176,7 +176,7 @@ class DevRunner {
       });
       const electronArgs = process.env.ELECTRON_ARGS;
       const args = electronArgs != null && electronArgs.length > 0 ? JSON.parse(electronArgs) : [`--inspect=${yield (0, _util().getFreePort)("127.0.0.1", 5858)}`];
-      args.push(path.join(projectDir, "dist/main/main.js")); // Pass remaining arguments to the application. Remove 3 instead of 2, to remove the `dev` argument as well.
+      args.push(path.join(projectDir, ".")); // Pass remaining arguments to the application. Remove 3 instead of 2, to remove the `dev` argument as well.
 
       args.push(...process.argv.slice(3)); // we should start only when both start and main are started

```

My dist file is also `dist/main/main.js`, but the problem is, that the `electron` binary file (in `node_modules/electron/dist/electron`) seems not correctly find the develop `node_modules` with `sqlite3` using `dist/main/main.js` as start file

Changing the start file to `.` and electron takes the start file from `main` in `package.json` (like in the packaged enviroment) and also find `node_modules` with the `sqlite3` module (This would also improves, if some developer not want to use `dist/main/main.js` as start file, currently it's just a hardcode path)

**Comment by loopmode** [comment]
Have a look at https://github.com/electron-userland/electron-webpack/issues/13

**Comment by ozelot379** [comment]
Thanks for the link to the other issue, but that isn't the same problem.

My problem isn't on the build rather the develop

But I noticed that the issue seems fixed in Electron 6 :)

**Comment by ozelot379** [comment]
I close this because it has resolved itself
