### ISSUE TITLE
[Add-ons] Less - Enable Inline JavaScript

### ISSUE THREAD

**Issue by neevany** [electron-userland/electron-webpack#312]
* **Version**: 21.0.11

* **Target**: mac

I am using [ant-design](https://github.com/ant-design/ant-design) and
I need to add a config to less-loader [ant-design/issues/7927](https://github.com/ant-design/ant-design/issues/7927#issuecomment-372513256) 
Config 
```
{ 
  loader: 'less-loader', 
  options: { javascriptEnabled: true } 
}
```
as i am getting this Error 
```
 ModuleBuildError: Module build failed (from ./node_modules/less-loader/dist/cjs.js):
.bezierEasingMixin();
  ^
  Inline JavaScript is not enabled. Is it set in your options?
```

How can i enable that configuration in less-loader

**Comment by loopmode** [comment]
Hi

You can 
1. define a custom webpack config module for the renderer in electron-webpack config
2. From your custom config module, export a function that receives the old webpack config and returns it after modifications
3. As modifications, in the config function, you can iterate config.rules and find the less loader
4. Once you found it, you can adjust its options

I'll post a link to another issue where something similar was needed for style loader

**Comment by neevany** [comment]
> Hi
> 
> You can
> 
> 1. define a custom webpack config module for the renderer in electron-webpack config
> 2. From your custom config module, export a function that receives the old webpack config and returns it after modifications
> 3. As modifications, in the config function, you can iterate config.rules and find the less loader
> 4. Once you found it, you can adjust its options
> 
> I'll post a link to another issue where something similar was needed for style loader
> 
> Update: Here is the mentioned other issue, have a look: [#296 (comment)](https://github.com/electron-userland/electron-webpack/issues/296#issuecomment-504652118)
> 
> I guess you would need something like this:
> 
> ```
>     const lessLoader = rule.use.find(use => use.loader === 'less-loader')
>     lessLoader.options.javascriptEnabled = true
> ```

Thank you, it worked 😀

**Comment by transtone** [comment]
https://github.com/webpack-contrib/less-loader/issues/350
