### ISSUE TITLE
html not refreshed in dev mode when using template

### ISSUE THREAD

**Issue by JuanIrache** [electron-userland/electron-webpack#313]
* **Version**: 
```
"electron": "^6.0.0",
"electron-webpack": "^2.7.4",
```

* **Target**: Dev on Windows, so far.

When running in dev mode, modifying js files refreshes the app, modifying css refreshes the css only, but modifying the html of the specified template does not change anything, so a manual refresh is needed. This is my config:

```
"electronWebpack": {
    "renderer": {
      "template": "src/template.html",
      "webpackConfig": "webpack.renderer.js"
    }
  }
```

**Comment by loopmode** [comment]
The problem is that your template is just in src, but not in one of the known/watched subfolders. If you move it inside src/renderer or src/common, it will be watched.

Let me know if you'd like to know details about it. It's due to a mechanism that is baked in. In your case, the fix is rather simple. In my case, it was the same symptom/problem, but the fix had to be much more complicated.

**Comment by loopmode** [comment]
Some details regardless of whether you ask for them :) for future readers/visitors.

There is a custom webpack plugin that handles file changes. It wants to decide whether a change was relevant for either the main or the renderer process, and it does it in a whitelist fashion. See https://github.com/electron-userland/electron-webpack/blob/d8cfe9ac18d6056ebb4cddbf4005c33178653e4f/packages/electron-webpack/src/targets/BaseTarget.ts#L142

If the changed file is not a child of either src/renderer, src/main or src/common, the change is simply ignored.

This is a massive problem if you try to have electron-webpack apps running in a yarn workspaces, where other workspace packages are linked to the root node_modules folder, which is obviously outside of the known/watched folders.
For that case I created https://www.npmjs.com/package/@loopmode/electron-webpack-config-yarn-workspaces - it [overrides the implementation of said plugin](https://github.com/loopmode/electron-webpack-config/blob/master/packages/yarn-workspaces/plugins.js#L10) to return true if the changed file was a child of one of the workspace packages

**Comment by JuanIrache** [comment]
That makes a lot of sense. Thank you for the comprehensive explanation

**Comment by JuanIrache** [comment]
That makes a lot of sense. Thank you for the comprehensive explanation
