### ISSUE TITLE
Make --progress optionnal

### ISSUE THREAD

**Issue by magne4000** [electron-userland/electron-webpack#319]
* **Version**: 21.2.0

* **Target**: any

Having `--progress` option enforced in `webpack-cli` floods travis build.
Here are my suggestions to fix this:
- Remove the forced `--progress` flag
- Enforce it only when building dev target
- Enforce it only when not in CI env

**Comment by loopmode** [comment]
You could try to get control over it via custom config. See https://stackoverflow.com/a/37664373/368254 and the docs here for how to customize webpack config.

**Comment by magne4000** [comment]
I tried but this particular flag seems to be CLI only

**Comment by loopmode** [comment]
Ah I see. It's hardcoded. Well.. there was one or two other issues that can be solved by supporting an env variable or a config value to make them optional. Feel free to submit a PR for this, else I'll take care of it soonish, e.g. coming weekend.

**Comment by loopmode** [comment]
@magne4000 The [code in question](https://github.com/electron-userland/electron-webpack/blob/0a9afdbdba96b21222dc41d7695f8f047df19d37/packages/electron-webpack/src/cli.ts#L26) doesn't have the configuration available yet, so we'd have to really do it with an env var, e.g. 
```
  if (!process.env.ELECTRON_WEBPACK_NO_PROGRESS) { 
    args.push("--progress")
  }
```
Which is a rather ugly solution.

However, it seems to me that you can actually just provide a `--no-progress` argument and it will be passed along and respected.

So, before we do anything rash, please try out `--no-progress` and report back if that is sufficient. Thanks.

**Comment by magne4000** [comment]
Ah yes it does work with `--no-progress`, nice catch! 🎉
![cloud strife](https://media.giphy.com/media/HCJFGKnYN90Ji/giphy.gif)
