### ISSUE TITLE
How to Silence Webpack Output

### ISSUE THREAD

**Issue by zeebenzene** [electron-userland/electron-webpack#322]
* **electron-builder Version**: 21.2.0
* **electron-webpack Version**: 2.7.4
* **electron-updater Version**: 4.1.2

* **Target**: win64 && macos

I have been using electron-webpack very heavily recently and have configured it to run from gitlab CI.  One of the things that gitlab CI does however is it captures all of the output for the percentage etc which makes the CI logs huge and a little bit difficult to read.  This is not so huge in the terminal because I suspect that a clear is called before every update. 

An example of the output is this small snippet but expanded to 3046 lines of output. 
~~~~
<s> [webpack.Progress] 58% [0] building 1000/1026 modules 26 active /usr/local/bin/builds/uvfbts25/0/org/app-name/node_modules/xmlbuilder/lib/XMLNode.js
<s> [webpack.Progress] 58% [0] building 1001/1026 modules 25 active /usr/local/bin/builds/uvfbts25/0/org/app-name/node_modules/xmlbuilder/lib/XMLNode.js
<s> [webpack.Progress] 58% [0] building 1002/1026 modules 24 active /usr/local/bin/builds/uvfbts25/0/org/app-name/node_modules/xmlbuilder/lib/XMLNode.js
<s> [webpack.Progress] 58% [0] building 1003/1026 modules 23 active /usr/local/bin/builds/uvfbts25/0/org/app-name/node_modules/xmlbuilder/lib/XMLNode.js
~~~~

Is there a way to silence this output on the webpack build process?  I've been looking and trying a few things in the webpack config options from default webpack such as setting stats options - however nothing seemed to work.

**Comment by loopmode** [comment]
We had a very similar issue just days ago: https://github.com/electron-userland/electron-webpack/issues/319

Try passing a `--no-progress` flag!

**Comment by zeebenzene** [comment]
You're a beautiful human. Thanks! That works perfect.
