### ISSUE TITLE
Typescript Configuration requiring StrictNullChecks

### ISSUE THREAD

**Issue by zeebenzene** [electron-userland/electron-webpack#323]
### Dependencies and Versions
    "electron-builder": "^21.2.0",
    "electron-updater": "^4.1.2",
    "electron-webpack": "^2.7.4",
    "electron-webpack-ts": "^3.2.0",

* **Target**: win, macos

### My Issue
I'm trying to include Material UI react components in my electron app and also use typescript.  This requires that I have the following options in my tsconfig:
~~~~
      "lib": ["es6", "dom"],
      "noImplicitAny": true,
      "noImplicitThis": true,
      "strictNullChecks": true,
~~~~
So I've extended electron-webpack's tsconfig as specified here:
https://webpack.electron.build/add-ons.html#adding-typescript-support-for-jsx-tsx-files
and also added the "jsx": "react" option to have a final tsconfig.json of the following:
~~~~
{
  "extends": "./node_modules/electron-webpack/tsconfig-base.json",
  "compilerOptions": {
      "lib": ["es6", "dom"],
      "noImplicitAny": true,
      "noImplicitThis": true,
      "strictNullChecks": true,
      "jsx": "react"
    }
  }
~~~~

However this causes issues with for example setting the mainWindow object to null on close to dereference the main window object as is done in this example: https://github.com/electron/electron-quick-start/blob/master/main.js

As such whenever I try to compile I get the following errors
~~~~
          TS2322: Type 'null' is not assignable to type 'BrowserWindow'.
~~~~

### My questions:
1. Do I  need to actually set the mainwindow to be null? 
2. Is it possible to have a tsconfig that only applies the necessary compiler options from material UI on the renderer bundle?

**Comment by b-zurg** [comment]
The solution is really to allow MainWindow to be null or of type BrowserWindow in the type declaration.  Then you can explicitly set it to be null instead of implicitly and that will solve the compiler errors.
