### ISSUE TITLE
Field descriptions in documentation?

### ISSUE THREAD

**Issue by twigs67** [electron-userland/electron-webpack#327]
Maybe I'm missing something, but I'm trying to understand what the various fields in the webpack config mean. For instance, "commonSourceDirectory"? 

Can this be found somewhere or how am I supposed to know what these mean?

**Comment by loopmode** [comment]
Hi! You're right, documentation could be better... :/ We really need some manpower here :) you probably have studied the docs already, but they mostly list what's available, not what it means.

Concretely about commonSourceDirectory, that's a folder that will be available to both the renderer and the main codebases.

Please note that typical electron boundaries still apply: A common source module that exports some object (e.g. a form of "Singleton"), required in both main and renderer code, will result in two "physical" copies/instances of that object at runtime, one in the main process and one in renderer process.
However, this is often useful for sharing utils, e.g. validators, or any kind of pure functions - data-in, some logic, data-out etc.

**Comment by twigs67** [comment]
@loopmode no worries. Thanks for clearing that up. If I can help with documentation, let me know.
