### ISSUE TITLE
Pass extended webpack.config.js to the CLI

### ISSUE THREAD

**Issue by marcoslhc** [electron-userland/electron-webpack#33]
**_This is a feature request_** I can look into it later to provide more details on how this could be done

There is an option to extend the webpack configuration but the payoff is to stop using the electron-webpack CLI which is less than desirable. We lose the automated start of the app, nice logging, etc.
It would be awesome if we had something like:
```sh
$ electron-webpack dev --config [ custom.renderer.webpack.config.js \ 
»                               , custom.dll.webpack.config.js]
```
or something similar.

**Comment by loopmode** [comment]
Also, I would suggest aiming for separate `--config` and `--dllConfig` args (config implicitly meaning "renderer config")

**Comment by SimulatedGREG** [comment]
I have an experimental branch that I was working on previously. I'll look back into that and report back.

**Comment by marcoslhc** [comment]
@loopmode It is a similar issue. I want to use something like this in webpack.config:
```
...
module: {
    rules: [
        ...
        { test: /\.scss$/, loader: 'css-loader!sass-loader?modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]' },
        ...
    ]
}
...
```

You can close this issue and continue the discussion though I think having a specific feature request issue to discuss is useful too.

**Comment by SimulatedGREG** [comment]
Going to close this in favor of #11. Please move further discussion there.

**Comment by loopmode** [comment]
@marcoslhc see https://github.com/electron-userland/electron-webpack/issues/11#issuecomment-332656173
