### ISSUE TITLE
How to import fonts from node_modules?

### ISSUE THREAD

**Issue by osenvosem** [electron-userland/electron-webpack#335]
* **Version**: 21.1.5

* **Target**: 

Getting the error when I'm trying to import a font package from node-modules like `typeface-roboto`.

```
@font-face {
^

SyntaxError: Invalid or unexpected token
    at new Script (vm.js:83:7)
    at createScript (vm.js:265:10)
    at Object.runInThisContext (vm.js:313:10)
```

`css-loader`, `file-loader`, `url-loader` are installed.

**Comment by loopmode** [comment]
@osenvosem what was the problem and how did you solve it?

**Comment by osenvosem** [comment]
> @osenvosem what was the problem and how did you solve it?

I'm not sure what was the problem, It just disappeared. Looks like it is related to caching or something.

**Comment by zhaoyao91** [comment]
same error when trying to install material-ui

**Comment by EloB** [comment]
I also have this exact error with the same library `typeface-roboto`.
