### ISSUE TITLE
issue with sass-loader ^8.0.0 prependData 

### ISSUE THREAD

**Issue by ovandenbos-imb** [electron-userland/electron-webpack#338]
with
    "electron-builder": "^21.2.0",
    "electron-webpack": "^2.6.2",
    "electron": "7.1.3",
    "electron-webpack-vue": "2.3.0"

    "webpack": "^4.41.2",
    "webpack-cli": "^3.3.10",
    "webpack-combine-loaders": "^2.0.4",

we do have an issue that is because 'prependData' is not applied.

               test: /\.scss$/,
                type: 'javascript/auto',
                use: [
                    'vue-style-loader',
                    'css-loader',
                    {
                        loader: 'sass-loader',
                        options:
                        {
                            sassOptions: {
                                includePaths: ['./src'],
                            },
                            prependData: '@import "./src/globals.scss";',
                        },
                    },
                ],
            },
            {
                test: /\.sass$/,
                type: 'javascript/auto',
                use: [
                    'vue-style-loader',
                    'css-loader',
                    {
                        loader: 'sass-loader',
                        options:
                        {
                            sassOptions: {
                                includePaths: ['./src'],
                            },
                            prependData: '@import "./src/globals.scss";',
                        },
                    },
                ],
            },

    ERROR in ./src/screens/IslandMenu.vue?vue&type=style&index=0&lang=scss& (./node_modules/mini-css-extract-plugin/dist/loader.js!./node_modules/css-loader/dist/cjs.js??ref--4-1!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/sass-loader/dist/cjs.js!./node_modules/vue-loader/lib??vue-loader-options!./src/screens/IslandMenu.vue?vue&type=style&index=0&lang=scss&)
    Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
    ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
    SassError: Undefined variable: "$color-greyblue-dark-transparent-medium".
            on line 235 of D:\Git\game-client\GameClientUI\src\screens\IslandMenu.vue
    >>   background-color: $color-greyblue-dark-transparent-medium;
    
       --------------------^
    
        at D:\Git\game-client\GameClientUI\node_modules\webpack\lib\NormalModule.js:316:20
        at D:\Git\game-client\GameClientUI\node_modules\loader-runner\lib\LoaderRunner.js:367:11
        at D:\Git\game-client\GameClientUI\node_modules\loader-runner\lib\LoaderRunner.js:233:18
        at context.callback (D:\Git\game-client\GameClientUI\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
        at Object.callback (D:\Git\game-client\GameClientUI\node_modules\sass-loader\dist\index.js:73:7)
        at Object.done [as callback] (D:\Git\game-client\GameClientUI\node_modules\neo-async\async.js:8067:18)
        at options.error (D:\Git\game-client\GameClientUI\node_modules\node-sass\lib\index.js:294:32)
     @ ./src/screens/IslandMenu.vue?vue&type=style&index=0&lang=scss& 1:0-348 1:364-367 1:369-714 1:369-714
     @ ./src/screens/IslandMenu.vue
     @ ./node_modules/babel-loader/lib??ref--0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/Author.vue?vue&type=script&lang=js&
     @ ./src/components/Author.vue?vue&type=script&lang=js&
     @ ./src/components/Author.vue
     @ ./node_modules/babel-loader/lib??ref--0!./node_modules/vue-loader/lib??vue-loader-options!./src/App.vue?vue&type=script&lang=js&
     @ ./src/App.vue?vue&type=script&lang=js&
     @ ./src/App.vue
     @ ./src/main.js
     @ multi ./node_modules/electron-webpack/vue-renderer-entry.js ./src/main.js

which happens if globals.scss is not present

**Comment by ovandenbos-imb** [comment]
tried another way, no luck - with sass-resources-loader

{
                test: /\.sass$/,
                type: 'javascript/auto',
                use: [
                    'vue-style-loader',
                    'css-loader',
                    {
                        loader: 'sass-loader',
                        options:
                        {
                            sassOptions: {
                                includePaths: ['./src'],
                            },
                        },
                    },
                    {
                        loader: 'sass-resources-loader',
                        options: {
                            sourceMap: true,
                            resources: [
                                './src/globals.scss',
                            ],
                        },
                    },
                ],
            },

**Comment by loopmode** [comment]
If your config exports an object, you will only ever extend the config. What you should do instead is change the existing loader; export a function, receive the config object, iterate rules, find loader, add options to it. Finally return modified config.

**Comment by ovandenbos-imb** [comment]
Thanks. I understand now I was not running against my own webpack.config 
re: https://webpack.electron.build/modifying-webpack-configurations#using-a-config-function

**Comment by loopmode** [comment]
Yeah, the docs example is actually quite close to what you need (finding a particular loader etc).
Feel free to share a snippet here once you have a concrete solution. I think we should start publishing packages with particular config modifier functions, basically we have the same possibilities as e.g. react-app-rewired, which has all kind of util functions like `addWebpackAlias`. We might even be able to use those directly BTW.
In this case, we might find something like this useful: `addSassOptions(config, options)`.
I did something similar [here](https://www.npmjs.com/package/@loopmode/electron-webpack-config-yarn-workspaces) for another situation. We could have a simple package name and a bunch of helper functions inside of it.
