### ISSUE TITLE
How to get app version?

### ISSUE THREAD

**Issue by twigs67** [electron-userland/electron-webpack#345]
Hello all,

I'm trying to get my app version, but the standard way, app.getVersion(), is pulling the electron version. 
Does anyone have a workaround for this? 

Thanks

**Comment by loopmode** [comment]
What do you mean by app version? If you refer to what's in your package.json, simply require and read it via `require('../relative/path/to/package.json').version`.

If you have a dynamic relative path, you could try the magic aliases, e.g. `'@/../package.json'`>

**Comment by twigs67** [comment]
@loopmode and to anyone else running into this issue. [This thread](https://github.com/electron/electron/issues/7085) cleared this up for me. 

Although, getVersion() will read the electron version in dev. For PR builds, it will always use the app.version in package.json.

**Comment by loopmode** [comment]
@twigs67 that does look quirky..as many things in electron world do :) luckily, here we have the luxury of webpack!
I'd still utilize webpack if you need the version reliably in different modules. Either using aliases (e.g. we already have the `@` to the `src` folder via default config, or you could even define an alias for `"package.json"`), or via `DefinePlugin` as in `new DefinePlugin({ APP_VERSION: require('./package.json').version })` and the use `APP_VERSION` as a global variable.

**Comment by twigs67** [comment]
v
<vv
