### ISSUE TITLE
We would like release 2.7.5

### ISSUE THREAD

**Issue by nicolas-van** [electron-userland/electron-webpack#346]
As far as I can see version 2.7.5 was only marked as a pre-release on github and last published version is still 2.7.4.

We would need a real release of 2.7.5, notably because it seems to contains a fix for this issue: https://github.com/electron-userland/electron-webpack/issues/83

**Comment by akozhemiakin** [comment]
Yes, it would be awesome to release 2.7.5. Currently we are forced to use 2.7.5 from our private registry to make things work well.

**Comment by kysley** [comment]
Definitely would like a release. This makes working with `eslint-plugin-react-hooks` impossible.

`React Hook useEffect has a missing dependency: '<your dep>'. Either include it or remove the dependency array.` is meant to be a reminder that you may run into a stale closure, but none of these reminders can exist 😕

**Comment by hodgef** [comment]
@loopmode @develar Any chance 2.7.5 can be released soon?

**Comment by nicolas-van** [comment]
OK, due to the Coronavirus I have to work at home and on a Windows machine where I encounter bug #83 and it's just a hell to do my work.

So, as a workaround I released an unofficial 2.7.5. If you want to use it just replace this line in your dependencies:

```
"electron-webpack": "2.7.4",
```

With this one:

```
"electron-webpack-release": "2.7.5-1",
```

I can't guarantee the release is perfect but it works for me.

**Comment by nicolas-van** [comment]
By the way for the maintainers: Come on guys, we're close to 9 months without any move on the repo.

This package is still used by a lot of persons. If you don't have any more time to manage it we can understand but at least make a call for new maintainers.

**Comment by develar** [comment]
2.8.0 released. Please try it.

**Comment by nicolas-van** [comment]
It works, thanks a lot. You can also close https://github.com/electron-userland/electron-webpack/issues/83 .
