### ISSUE TITLE
Downgrade html-loader to 0.5.5 to resolve js-yaml audit warnings

### ISSUE THREAD

**Issue by meszaros-lajos-gyorgy** [electron-userland/electron-webpack#348]
Hello! I'm opening this ticket as a followup to https://github.com/electron-userland/electron-webpack/issues/300

Based on the conversation with the author (https://github.com/webpack-contrib/html-loader/pull/201)  of `webpack-contrib/html-loader`, the latest version, `1.0.0-alpha.0` is not intended for production use and the author suggests using version `0.5.5` for production.

The 1.0.0 line is still being actively developed with no release date and the author is not showing any will to push a hotfix with just the updated version of `htmlnano`.

I suggest downgrading `webpack-contrib/html-loader` to `0.5.5` here, which does not have `html-nano` as a dependency: https://github.com/electron-userland/electron-webpack/blob/master/packages/electron-webpack/package.json#L37

If that is not a viable solution, or there are api changes between version `1.0.0-alpha.0` and `0.5.5`, then I'm more, than happy to fork the repo and release a hotfix myself in a separate package.

**Comment by mayeths** [comment]
The lastest commit here was on Jul 10, 2019, I don't think they still maintain this repo ☹.

The [package.json](https://github.com/electron-userland/electron-webpack/blob/master/package.json) has `resolutions` field but I'm confused why it's not working
```
"resolutions": {
    "js-yaml": "^3.13.1"
  },
```

**Comment by loopmode** [comment]
@mayeths the resolutions field is a yarn feature, so it will not work with npm install. Also, it could be that a lockfile entry interferes, possibly removing the lockfile could help.

**Comment by meszaros-lajos-gyorgy** [comment]
Heads up! Version `1.0.0` of `webpack-contrib/html-loader` was released recently: https://github.com/webpack-contrib/html-loader/releases/tag/v1.0.0

**Comment by b-zurg** [comment]
awesome! It looks like we can't use the new version yet because of https://github.com/electron-userland/electron-webpack/issues/357 but I'm hoping that won't be a hard problem to solve.

**Comment by meszaros-lajos-gyorgy** [comment]
The author stated, that it's not a fix for 1.0.0-alpha, but a complete rewrite, so I assume it's not 100% compatible.

**Comment by alexweber** [comment]
Seems #357 should fix this
