### ISSUE TITLE
Compiling a DLL results in a error when attempting to load the vendor file in dev

### ISSUE THREAD

**Issue by glek** [electron-userland/electron-webpack#359]
* **Versions**: 
  * `electron-builder`: 22.4.1
  * `electron-webpack`: 2.8.2

* **Target**: Windows, `dev` with a vendor DLL

After creating a simple Electron app that uses React/React DOM and puts both in a vendor file, I cannot start the project in dev mode.

![image](https://user-images.githubusercontent.com/1039449/79075955-17072580-7cc4-11ea-8b22-4a15297493a4.png)

I believe this is related to the changes done to address #357 which has caused Webpack, or at least `html-loader` to try to `require` the vendor file instead of fetching it from the dev server.

One possible fix would be to set `attributes=false` in the `html-loader` call inside the renderer target configurator. Alternatively, it may be possible to disable just the processing of `src` attributes on `script` tags. See https://webpack.js.org/loaders/html-loader/#attributes for more details on that.

**Comment by twelvescore** [comment]
I also encountered the same problem, how can I quickly solve it?

**Comment by glek** [comment]
> I also encountered the same problem, how can I quickly solve it?

I'd recommend taking a look at the open PR #366. It provides a solution. This can be applied locally by modifying your `node_modules` but a permanent fix is pending on that PR being merged.

**Comment by twelvescore** [comment]
> > I also encountered the same problem, how can I quickly solve it?
> 
> I'd recommend taking a look at the open PR #366. It provides a solution. This can be applied locally by modifying your `node_modules` but a permanent fix is pending on that PR being merged.

Temporarily resolved, thank you very much, and hope to release the revised version as soon as possible

**Comment by glek** [comment]
Is there going to be any movement on this, @develar, or should I investigate alternative solutions to using Webpack with Electron?
