### ISSUE TITLE
typescript :Module not found: Error: Can't resolve

### ISSUE THREAD

**Issue by FishOrBear** [electron-userland/electron-webpack#365]
[electron-webpack-quick-start-master.zip](https://github.com/electron-userland/electron-webpack/files/4530215/electron-webpack-quick-start-master.zip)

![image](https://user-images.githubusercontent.com/19372111/80236248-746c8080-868d-11ea-84c2-0d1893cecac7.png)

![image](https://user-images.githubusercontent.com/19372111/80236272-80f0d900-868d-11ea-9810-5958628c91f3.png)

**Comment by loopmode** [comment]
I believe this happens when you didn't install `electron-webpack-ts`. (See https://webpack.electron.build/add-ons#typescript)

SImply add it as a dependency and it should work:

```
yarn add --dev electron-webpack-ts
```

**Comment by FishOrBear** [comment]
Thanks, you are right
