### ISSUE TITLE
Hot reload stopped working

### ISSUE THREAD

**Issue by walleXD** [electron-userland/electron-webpack#37]
Hi,

Hot reload suddenly stopped working for me and I have no clue why. As things stand, one clue I got seems to be the my `if (module.hot)` check doesn't run when I make changes. On the console is just say `App hot update....` & `App updated. Recompiling...` but my `react-hot-loader` doesn't run as `module.hot` doesn't seem to be working. Any ideas?

My `index.js` file:
```es6
import { AppContainer } from 'react-hot-loader'
import React from 'react'
import { render } from 'react-dom'
import { Provider as ReduxProvider } from 'react-redux'
import Router from 'react-router-redux/ConnectedRouter'
import { replayActionRenderer } from 'electron-redux'
import { Provider as RebassProvider } from 'rebass'
import 'typeface-roboto/index.css'
import 'mdi/scss/materialdesignicons.scss'
import './lib/icon.scss'

import history from './lib/history'
import store from './lib/store'
import App from './containers/App'

replayActionRenderer(store)

const renderApp = Component => render(
  <AppContainer>
    <ReduxProvider store={store}>
      <Router history={history}>
        <RebassProvider>
          <Component />
        </RebassProvider>
      </Router>
    </ReduxProvider>
  </AppContainer>,
  document.getElementById('app')
)

renderApp(App)

if (module.hot) module.hot.accept('./containers/App', () => renderApp(App))
```

**Comment by AndreyWeber** [comment]
@walleXD Probably this happens because you need to re-read `App` component from file to reflect changes you've done in it or down the components tree. Like it was mention in other thread #29 something like that:
```javascript
if (module.hot) {
    module.hot.accept('./App', () => {
        const NextApp = require('./App').default;
        ReactDOM.render(<NextApp />, rootEl);
    });
}
```
This `const NextApp = require('./App').default;` statement required to re-read `App' component.

Have you tried to put `console.log()` inside your `if (module.hot)` branch to be sure, that program flow hit it?

**Comment by walleXD** [comment]
@AndreyWeber I tried to setup the hmr using 

```es6
if (module.hot) {
  console.log('WORKS!')
  module.hot.accept('./containers/App', () => renderApp(App))
}
```

The `WORKS` only shows up in console during initial boot. After every change there after, there's no `module.hot` and so no `HOT` output in the console. All my code is in this [repo](https://github.com/walleXD/Kasset)

**Comment by walleXD** [comment]
My guess this had happened was due to Webpack related package mismatch. So, will close this ...
