### ISSUE TITLE
As 2020, how does this work fine with React?

### ISSUE THREAD

**Issue by jordymeow** [electron-userland/electron-webpack#371]
I am using all the latest versions. 

I wanted to use electron-webpack as it claims to be simple. In my case, it should have been super easy as I am running a simple project using React and Electron. However, that is not the case, and digging into all the issues here and the examples on this repo, it feels like this tool makes just everything more opaque while not being that simpler. I just hope I am wrong.

As of May 2020, does this actually work fine with React? Is there a repo somewhere, with the bare minimum of modules and configuration? The current repo isn't helpful, it's simply too big to adapt and doesn't use React anyway.

If you are curious, my issue is that I could make it work with my project in dev mode, but after building a package I get this error in the dev tools console:

`Cannot find module 'react'`

I am only using this tool, I have no webpack configuration files of my own (but this tool definitely has, though I can't see them), and only using "@babel/preset-react" in my .babelrc. 

I would like to confirm I am not making a mistake by using electron-webpack, it seems like an official package, but maybe it is not and it only works in a specific case (and which doesn't include React). Thanks a lot and sorry, I just would like to make this clear for users of React as well.

**Comment by MatthewRorke** [comment]
Add this to your postinstall script call:
` "postinstall": "electron-builder install-app-deps",`
Run the normal install process with your package manager (npm/yarn).
Try build again.

**Comment by jordymeow** [comment]
@MatthewRorke Thanks so much for this... I have no idea why it worked, but it did!
