### ISSUE TITLE
Material UI: several instances of `@material-ui/styles` initialized

### ISSUE THREAD

**Issue by Achder** [electron-userland/electron-webpack#372]
Hey guys,

I'm having trouble with React and Material UI. 
The app is running, but as far as I can tell there are some styling issues.
In dev-tools I get the following warning:
> It looks like there are several instances of `@material-ui/styles` initialized in this application.
> This may cause theme propagation issues, broken class names, specificity issues, and makes your application bigger without a good reason.
> 
> See https://material-ui.com/r/styles-instance-warning for more info.

The link has some solutions to this problem, but I'm not sure how to implement. 
Is this something I can resolve using electron-webpack?

@material-ui/core: ^4.9.13,
electron: ^8.2.5,
electron-webpack: ^2.8.2,
react": ^16.13.1,
react-dom: ^16.13.1,
webpack: ^4.43.0

Thanks in advance!

**Comment by Achder** [comment]
Took a while, but it was as simple as adding this to your packages.json:
```
{
  ...
  "electronWebpack": {
    ...
    "whiteListedModules": ["@material-ui/core"]
  },
  ... 
}
```
Notice: I don't whitelist the material-ui/styles modules, but material-ui/core.

**Comment by loopmode** [comment]
Hi. I didn't want to respond prematurely so I asked a buddy yesterday who had the exact same problem a while ago, sending him a link to this issue, but it seems you were quicker :)

I guess the docs should emphasize the whitelisting much more. 
Adding dependencies to webpack externals is pretty important for electron apps - however, only for dependencies of the main process, and basically never for renderer dependencies. What electron-webpack does is still putting _all_ dependencies to webpack externals, unless you whitelisted them manually.
So typically, users run into this issue, then need to figure this out and finally remove some of their frontend-related dependencies from webpack externals by adding them to whitelistedModules.

In my experience, most users of electron-webpack work _only_ in the renderer process and hardly to heavy lifting in the main process. In that case it also helps to just override the webpack config and set externals to an empty array - no whitelisting anything, no webpack externals for anything, and it "just works" until you actually have some dependencies for the main process that need to be webpack externals.
