### ISSUE TITLE
Dev - does not launch window

### ISSUE THREAD

**Issue by parliament718** [electron-userland/electron-webpack#381]
I've experienced this issue on and off for very long time where electron-webpack fails to open the electron window after compiling. There are no actual errors in the compilation 

![Screen Shot 2020-06-27 at 8 30 30 AM](https://user-images.githubusercontent.com/3580270/85922354-8ebf0800-b850-11ea-9ef4-37503d9ad868.png)
![Screen Shot 2020-06-27 at 8 30 45 AM](https://user-images.githubusercontent.com/3580270/85922355-8ebf0800-b850-11ea-8a2a-5fb9b2b3ae20.png)
![Screen Shot 2020-06-27 at 9 21 54 AM](https://user-images.githubusercontent.com/3580270/85923249-af3e9080-b857-11ea-8a9b-487734043ea1.png)

There's no indication of failure. How can I investigate this issue? Is there a way to turn up the logging or something.

Is there a way to manually launch the window if this happens?

Can this be caused by warnings? I have some of those too such as 
"Add only entry points to the 'files' or 'include' properties in your tsconfig"

I'm trying to resolve that error seperately as my tsconfig looks totally normal, I only include entry points.

I'm on MacOS using latest electron-webpack (2.8.2) and electron-builder (22.7.0)

**Comment by parliament718** [comment]
The problem stopped so I closed this issue, but 30 minutes later it came back. This literally happens randomly, sometimes without a single code change. I can run **electron-webpack dev** once and it works, and then run it again and it doesn't work (no window). I've spent countless hours on this problem over past few months thinking that there is a problem with my code but it always goes away randomly without me being able to learn anything about it.

**Comment by parliament718** [comment]
I think warning do affect this. I seem to have gotten past it once by using some webpack plugins to ignore warning.


`
const FilterWarningsPlugin = require('webpack-filter-warnings-plugin');
const IgnoreNotFoundExportPlugin = require('ignore-not-found-export-plugin');

plugins: [
            new FilterWarningsPlugin({
                exclude: /Critical dependency: the request of a dependency is an expression/,
            }),
            new IgnoreNotFoundExportPlugin(['IMarketApi', 'IBar']),
        ],
`

**Comment by loopmode** [comment]
You said there were no errors - red messages - and I assume there were warnings - yellow messages. Is that the case?  

There is a known issue where compiler warnings cause the startup to fail. 

There was a PR that was supposed to fix the problem, but apparently the problem persists.
One workaround is to adjust eslint settings so you don't have warnings. The better workaround is to not have warnings, e.g. don't push with warnings (e.g if you work in a team and don't want to annoy your teammates) or generally clean up warnings before stopping work (as to not annoy yourself once you come back to work later).
A proper fix that allows the window to be opened despite of warnings would be best, of course (PRs welcome).

**Comment by parliament718** [comment]
I'm back and it's happening again. Was just working 15 minutes ago with trivial code changes in between. No warnings this time. Tried deleting and recompiling bunch of times. Seems ridiculous but I expect the problem to just "go away soon", as it usually does of its own volition.

**Comment by parliament718** [comment]
This problem continues to haunt my application. It's come and go over 20 times and is usually caused by absolutely nothing. Meaning the "solution" is to comment out my most recently changed lines of code (which contain no errors, compile or otherwise), let it compile and launch, then go back and remove those comments and compile again the same exact code, now working again.

There are otherwise no errors in the compilation and absoutely no info is given what might be causing it. If I forget what my "most recently changed lines" are, then Im in for a wild ride of having to systematically comment out/undo all my recent changes part by part until I find the culprit, comment, compile, and uncomment it.

**Comment by parliament718** [comment]
Turns out this was not due to electron-webpack but rather electron-window.

In the electron-window source there's some code like

```
win.webContents.once('did-finish-load', function () {
    callback.apply(this, arguments)
  })
```

The event name there needs to be changed to ```ready-to-show```.

I use a postinstall script to monkey patch it

```"postinstall": "sed '37s/did-finish-load/ready-to-show/' node_modules/electron-window/lib/main.js > temp_file.js && mv temp_file.js node_modules/electron-window/lib/main.js"```
