### ISSUE TITLE
Css background image from static assets

### ISSUE THREAD

**Issue by Achder** [electron-userland/electron-webpack#386]
I'm using electron webpack to bundle my app. I want to display an image as a background image of a div container but I can't get it to work. It works in an img tag. The img tag looks like this:

```
<img src={path.join(__static, 'image', 'background.png')}/>
```

My css like this:

```
backgroundImage: `url('${path.join(__static, 'image', 'background.png')}')`
```

In my webpack config:

```
module: {
  rules: [
    {
      test: /\.(png|svg|jpg|gif)$/,
      use: ['file-loader']
    }
  ],
}
```

I'm using React and Material UI.
Please help

**Comment by loopmode** [comment]
Hi. Have a look at https://github.com/electron-userland/electron-webpack/issues/241#issuecomment-482526778

**Comment by Achder** [comment]
Wow, thanks for the quick reply. That actually worked. Big thanks!

**Comment by loopmode** [comment]
Glad I could help :) happy hacking!
