### ISSUE TITLE
Loader Config for SASS

### ISSUE THREAD

**Issue by AlexandreKilian** [electron-userland/electron-webpack#39]
according to the documentation, using the sass-loader should be enabled as an add-on (https://webpack.electron.build/add-ons#sassscss)

I found myself having to manually add the configuration for handling sass-files in EVERY component, which then looks like this:

`import { text } from '!style-loader!css-loader?modules&localIdentName=[name]---[local]---[hash:base64:5]!sass-loader!./Home.scss';`

using a predefined configuration, this should easily be configurable to only be `import { text } from './Home.scss';` which is how I usually set it up in my webpack configuration. the documentation on the sass-loader unfortunately is really brief, and I couldnt find any documentation on the configuration of loaders and rules. Is there some more extended documentation on this topic or is this the intended usage? because having multiple lines like this and having to write the exact loader rules in every file seems a bit counter intuitive...

**Comment by loopmode** [comment]
That is very weird. Something else must be wrong.. I'm using scss all over the place without issues:
```
import css from './Gears.scss';
...
<div className={css.Gears}>...</div>
```

I am using
```

    "electron-webpack": "^1.6.1",
    "node-sass": "^4.5.3",
    "sass-loader": "^6.0.6",

```

**Comment by AlexandreKilian** [comment]
okay, interesting, if I prefix it `:local ` it works, without it not unfortunately... I can't find anything about that prefix in the sass-documentation, where did you take that from?

**Comment by loopmode** [comment]
Yeah there won't be anything on sass side, as it's not part of it. It's part of how webpack setup handles it. In this case it's https://github.com/webpack-contrib/css-loader#modules

**Comment by darrenmothersele** [comment]
What if I'm importing third party sass file and I can't add :local? In fact, if I want to import CSS (SASS) into the global scope?

**Comment by loopmode** [comment]
@darrenmothersele That shouldn't be much of a problem, as you probably would not try to access "modules" inside those global styles.

If you just do  `import "bootstrap.scss"` or so, everything works fine.

You don't _need_ to add any `:local` stuff as long as you don't want to access it via `import styles from "thefile.scss"` and `<div className={styles.something}>`
