### ISSUE TITLE
index.ejs template issues with nodeIntegration:false for recommended Electron security

### ISSUE THREAD

**Issue by iRyanBell** [electron-userland/electron-webpack#392]
Using the latest version of `electron-builder` targeting an electron app, I receive a warning in the console that `nodeIntegration` _should_ be set to `false`. Leaving this set to `true` (unless specifically required) is listed as a bad practice with major security ramifications: https://www.electronjs.org/docs/tutorial/security

Flipping this switch leads to errors like these from the renderer's index:
- `require is not defined`
- `module is not defined`

Adding a new `index.ejs` template within the `src` directory rebuilds a custom index, however, the dynamic ejs templating syntax fails to parse from this .ejs file, and the require() and module() scripts are still injected into the custom template.

What are the recommended configuration changes to migrate from a nodeIntegration to a `preload` webPreferences?

**Comment by j3g** [comment]
@iRyanBell  any luck getting this resolved? I'm looking for work arounds. This project is stale and broken on many accounts.

**Comment by ghost** [comment]
> @iRyanBell any luck getting this resolved? I'm looking for work arounds. This project is stale and broken on many accounts.

I'd recommend checking out Nextron or other offerings that roll out a more updated config.
