### ISSUE TITLE
Suggestion: easy way to set index.html template

### ISSUE THREAD

**Issue by LeDominik** [electron-userland/electron-webpack#40]
It would be _really really_ awesome if there was a simple way (in the config with one setting) to set the [template webpack uses](https://webpack.js.org/plugins/html-webpack-plugin/) for `index.html` generation. It's needed quite often, to _just_ add a `CSS` here and there, some meta-tags, etc...

**Comment by kontrollanten** [comment]
Yes, there would be great to have the option to not use any JS template renderer to use this package. Wouldn't there be a good solution to skip the auto generation of index.html if src/renderer/index.html exists?

**Comment by LeDominik** [comment]
I just need some way to dig into it; and AFAIK the template linked is the technique electron-webpack uses, so I thought why not expose it. In the end it's pretty cool that Webpack creates it and adds all the stuff needed for HMR in a failsafe way, so no risk for people to get the `index.html` wrong and post error reports all the time.

**Comment by LeDominik** [comment]
Wohooooo, this should _totally_ solve it: https://github.com/electron-userland/electron-webpack/commit/70bfa7df3f028750aee33fd82b0872042d65f7d8

**Comment by mafar** [comment]
@LeDominik  how did u solve it ?

**Comment by fabiospampinato** [comment]
I've added a way of overriding the default HTML template in #261, this should greatly help in solving this issue.

**Comment by shahkeyur** [comment]
Anyone else looking for the solution, you can find doc [here](https://webpack.electron.build/configuration). Feel free to reopen the issue if still having any issues. @loopmode Can you close the issue please?
