### ISSUE TITLE
db files not included in package

### ISSUE THREAD

**Issue by jfaquinojr** [electron-userland/electron-webpack#41]
node: 8.6.0
npm 5.3.0
yarn 1.1.0
OS: Windows 10

Here is my original folder structure

root
├── data
│       └── mydatabase.db3
├── src
│       ├── main
│       │         └── index.js
│       ├── renderer
│       │          └── index.js
│       └──
└── package.json

I want to have the db3 file included in the package. 

I tried moving the folder around, inside src, inside common, and even static, but still not included in the package when i do yarn dist.

How can I do this?

Awesome project btw!

**Comment by walleXD** [comment]
if you want to include it with the app, put it in the static folder as it's included as it with the app. Alternatively you can create the db on load in the user's appropriate app data directory

**Comment by SimulatedGREG** [comment]
Yes, that's correct. To anybody reading this later, if you need **any** file to exist in production builds, then place it within the `static/` directory.

Related: https://webpack.electron.build/using-static-assets
