### ISSUE TITLE
app.setAsDefaultProtocolClient

### ISSUE THREAD

**Issue by couturecraigj** [electron-userland/electron-webpack#419]
* **Version**: 
"electron": "8.2.0",
"electron-builder": "^22.4.1",
"electron-webpack": "^2.8.2",

* **Target**: 
windows 10

I am trying to setAsDefaultProtocol in development.  I am getting an error
![2020-12-31 21_52_22-● package json - crm-desktop-app - Visual Studio Code](https://user-images.githubusercontent.com/6254360/103433206-d1242180-4bb2-11eb-9800-8d688277400c.png)

I am unsure how to troubleshoot this.  Can I get any assistance at all?

**Comment by loopmode** [comment]
https://github.com/electron/electron-api-demos/issues/273#issuecomment-262152112

**Comment by couturecraigj** [comment]
Thank you.
