### ISSUE TITLE
Support for tsx as entry file

### ISSUE THREAD

**Issue by Raathigesh** [electron-userland/electron-webpack#42]
Thank you for this excellent project. 
Is there any guide on how to configure a React project with typescript with electron-webpack?

**Comment by Raathigesh** [comment]
I suppose I have to modify the webpack config through `electronWebpack` configuration.  Should have read the instructions. Closing this for now. Please let me know if there is an easy way out without modifying the webpack config.

**Comment by develar** [comment]
We do support `tsx` file extension. What error do you have?

**Comment by resir014** [comment]
Hey @develar, I'm having this issue as well.

I want to set my entry point is `index.tsx` since I'm using React, but unfortunately it's not included in [this line](https://github.com/electron-userland/electron-webpack/blob/master/packages/electron-webpack/src/main.ts#L335) And TypeScript won't recognise JSX-enabled TypeScript files unless it has a `.tsx` extension...

And yeah, I have followed all the TypeScript instructions.

**Comment by resir014** [comment]
@develar Actually, I just found a weird workaround that works:

Have your *actual* app entry point at a different filename, something like `app.tsx`, and on your app's `index.ts` file, simply include this:

```ts
import './app'
```

**Comment by knpwrs** [comment]
I'm experiencing this same issue and thought of making an `index.ts` to point at `app.tsx` but I don't really consider that to be a solution. @develar is there any chance of getting support for `tsx` entry files? I see the `extraEntries` option for the main process, but this isn't "extra" and I want to do this in the renderer process.

**Comment by resir014** [comment]
@knpwrd This is already fixed. Try renaming your entry point to `index.tsx`

**Comment by ChrisEdgington** [comment]
I started a project with your current release - 2.0.1. Everything worked great until I followed instructions for adding typescript support. That worked fine until I went to convert my .jsx files to .tsx, and then I received errors in the build. The errors were resolved by adding the jsx:react option to the tsconfig.json as documented above. Therefore, I created a branch that adds this to the documentation.

**Comment by ChrisEdgington** [comment]
How should I go about getting this PR'ed ... should this issue be reopened, should I create a new issue? FWIW - here is my branch with the doc change: https://github.com/ChrisEdgington/electron-webpack/tree/document-typescript-jsx-support
