### ISSUE TITLE
Cannot specify modified webpack config

### ISSUE THREAD

**Issue by eamiralian** [electron-userland/electron-webpack#43]
Trying to follow the example [here](https://webpack.electron.build/modifying-webpack-configurations), after adding the `webpackConfig` key to the `renderer` object, I get this error when I run `electron-webpack dev`

> Error: Configuration is invalid.
> &nbsp;&nbsp;&nbsp;&nbsp;configuration.renderer should be one of these:
> &nbsp;&nbsp;&nbsp;&nbsp;object { dll?, sourceDirectory? } | {
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"type": "null"
> &nbsp;&nbsp;&nbsp;&nbsp;}
> &nbsp;&nbsp;&nbsp;&nbsp;Details:
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;* configuration.renderer has an unknown property 'webpackConfig'. These properties are valid:
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;object { dll?, sourceDirectory? }
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;* configuration.renderer should be null:
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; {
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"type": "null"
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; }

I've tried specifying this in both `package.json` and `electron-webpack.json`, neither work. I've been able to get other settings such as `title` working in the `electronWebpack` config object, the problem seems specifically related to the `webpackConfig` key.
 
> "electronWebpack": {
>&nbsp;&nbsp;&nbsp;&nbsp;"renderer": {
>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"webpackConfig": "webpack.renderer.additions.js"
>&nbsp;&nbsp;&nbsp;&nbsp;}  
> }

**Comment by develar** [comment]
electron-webpack version? 1.9.0 is required.

**Comment by eamiralian** [comment]
Whoops, was still on 1.8.0, didn't realize it was updated the day after I first grabbed it; sorry!
