### ISSUE TITLE
rendering react-router-dom hooks cause hooks rules error

### ISSUE THREAD

**Issue by justin-hackin** [electron-userland/electron-webpack#435]
* **Version**: 
`    "electron-webpack": "^2.8.2"`

[This repository](https://github.com/justin-hackin/electron-webpack-react-router-dom-hooks-broken) demonstrates that when a component with react-router-dom hooks is rendered within a Route, the application throws an error suggesting the rules of hooks have been violated. [This repository](https://github.com/justin-hackin/react-router-hooks-working) shows the same App is working in the context of a create-react-app. 

In order to reproduce the issue, click the "About" link in the app. In the working example, a button is rendered and clicking on it changes the route to the Topics section. In the bugged example, the app crashes.

Variations that did not prove any fix:
- use of BrowserRouter or MemoryRouter
- using the `render` prop of the Route with an anonymous function component that renders the About section

**Comment by loopmode** [comment]
Please search the existing issues. There's plenty similar ones. If you wanna get there more quickly or directly, search for "whitelisting".

**Comment by justin-hackin** [comment]
Yes, adding the package `react-router-dom` to the whitelist fixed my issue, I had searched issues on the  `react-router-dom`  but forgot to take a closer look here , thanks for identifying the dupe

**Comment by loopmode** [comment]
If I only had a dime for every time someone faces this issue 🙂
