### ISSUE TITLE
Error on getting the server port when upgrading to 1.9.0

### ISSUE THREAD

**Issue by resir014** [electron-userland/electron-webpack#48]
Seems like 1.9.0 introduced a new bug regarding reading the dev server port.

```
C:\Users\Resi\Projects\electron-webpack-quick-start-master> yarn dev
yarn run v1.2.1
$ electron-webpack dev

C:\Users\Resi\Projects\electron-webpack-quick-start-master\node_modules\electron-webpack\src\util.ts:40
        const port = server.address().port
                            ^
TypeError: Cannot read property 'port' of null
    at Server.server.listen (C:\Users\Resi\Projects\electron-webpack-quick-start-master\node_modules\electron-webpack\src\util.ts:40:29)
    at Object.onceWrapper (events.js:314:30)
    at emitNone (events.js:110:20)
    at Server.emit (events.js:207:7)
    at emitListeningNT (net.js:1371:10)
    at _combinedTickCallback (internal/process/next_tick.js:135:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by Alexmurder** [comment]
same question.

**Comment by eamiralian** [comment]
I had the same issue, running `yarn cache clean` resolved it.

**Comment by resir014** [comment]
@eamiralian Hm, I tried that, even deleted `yarn.lock` and reinstalled everything, still didn't work.

**Comment by walleXD** [comment]
@resir014 I would suggest deleting `node_modules` folder and reinstalling all your packages. Also, make sure to remove all other packages that might to run with webpack dynamically. I had a similar situation and the culprit was the `react-script` package

**Comment by develar** [comment]
Please ensure that you use NodeJS 8.

**Comment by loopmode** [comment]
I get that error many times during development. But in my case (Windows) it's because I killed the app and dev-server and try to start again - but the original processes are still running and windows hasn't terminated them yet.
I use `taskkill /F /IM node.exe /T` in these situations, after that, the error is gone (and so are any other node processes of course :))

**Comment by develar** [comment]
I hope fix in the 1.10.0 will help.

**Comment by loopmode** [comment]
I just had the error. Instead of killing all node.exe as usual, I Installed 1.10.0 tried again - and it worked!

**Comment by develar** [comment]
@loopmode Thans for verification, I have marked 1.1.0 as latest.
