### ISSUE TITLE
.html and .css files don't load correctly

### ISSUE THREAD

**Issue by YonatanKra** [electron-userland/electron-webpack#50]
I have a working electron app.  I've added electron-webpack to it.
When compiling with webpack, it throws a warning that .html and .css files cannot be parsed.
I've added the `css-loader` and `html-loader` plugins.
My webpack config:
```
module.exports = {
    entry: "./src/app.js",
    module: {
        loaders: [
            {
                test: /\.css/,
                loaders: ["style-loader", "css-loader"]
            },
            {
                test: /\.(png|jpg|gif)$/,
                loaders: ["url-loader?limit=5000&name=img/img-[hash:6].[ext]"]
            },
            {
                test: /\.html$/,
                loaders: ["html-loader"]
            }
        ]
    }
};
```
My `.html` file is loaded using `loadURL` and the `.css` files are loaded from inside the template (via the `link` tag).

Is there anything else I need to do in order to make it work?

**Comment by walleXD** [comment]
`electron-webpack` includes all the above loaders but you can't load files like this. During development, `electron-webpack` serves the `html`, `css` & `js` files using `webpack dev server` while during production they are built out into the dev folder. You cannot load raw `html` files development if you want to use the build `webpack` build pipeline

**Comment by SimulatedGREG** [comment]
To add some more to what @walleXD said, `electron-webpack` currently assumes that you don't have any sort of entry `index.html`. Any html, css, or js files must be included through JavaScript. Make sure to checkout out https://github.com/electron-userland/electron-webpack-quick-start and look into the provided file structure to understand how things are working.
