### ISSUE TITLE
Not allowed to load local resource error

### ISSUE THREAD

**Issue by YonatanKra** [electron-userland/electron-webpack#51]
I've read several cases of this error - none has helped to resolve the issue.  In order to verify my code is not the cause I've done the following:

1. I've created a new project of the official electron-quick-start (just forked it).
2. I've added electron-builder and it works:
https://github.com/YonatanKra/electron-quick-start/tree/building-app
3. Then I've added electron-webpack and it doesn't work:
https://github.com/YonatanKra/electron-quick-start/tree/adding-webpack

Is there anything I'm missing in order to make this work?

**Comment by walleXD** [comment]
@YonatanKra you have to set make `render` & `main` folders inside a `src` folder. `electron-webpack` then runs `index.js` file from those folders. Looks at the docs for [reference](https://webpack.electron.build/project-structure)

**Comment by YonatanKra** [comment]
@walleXD thanks.
The docs also say:

> electron-webpack does its best to not impose or encourage any sort of project structure or build cycle.

From what I understand in the docs, I can set a different main folder (via the `main.sourceDirectory` attribute).  In addition, I can set `renderer.sourceDirectory` to null in order to avoid bundling of renderer.
It does compile (I can see my `main.js` file) , and builds correctly (I get an installer file) but when I run my packaged app, it shows the above-mentioned error.
Let's assume my project is already set like this:
|- src
| |- module1
| | |- module1.js
| | |- module1.html
| |- app.js

`app.js` requires `module1` which calls `loadURL` with `module1.html`.
It works fine when I run `yarn dev` and when I just build using `electron-builder`,  but shows the error when running the build after compiling with `electron-webpack`.

**Comment by walleXD** [comment]
If you want to take this approach, you are better off not using webpack as it will make the whole thing more complicated as you would have to manually handle html and associated js files. 

Is there any reason you need a custom html page and not use the renderer webpack build?

**Comment by YonatanKra** [comment]
For once, this is the quick start guide of electron, so I assume one would like to stat there and move on to add more stuff (for instance - I open more than one window - each with its own .`html` template).
As far as I can tell, in the renderer the html content is loaded via code and not from files.
Eventually, what happens is the while using `dev` everything works fine, but when I try to build with `electron-builder` it breaks (with the error).  
Is there a way to use the external files? What do you mean by "manually handle html files"? Doesn't `html-loader` take care of these?
Thanks!

**Comment by walleXD** [comment]
`electron-webpack` is geared more towards more SPA style apps and `webpack` generates the html. The option to not use the built in renderer webpack process is geared towards tools like `nextjs` or `nuxtjs`, which uses webpack too. The template you had is much better for more vanilla approach, i.e no built tools. If you want to still use this template, with a build tool, `electron-compile` is a much better fit

**Comment by develar** [comment]
Please use https://github.com/electron-userland/electron-webpack-quick-start as a reference app and if need, explain why it is not suitable for you.

**Comment by develar** [comment]
In general — forget about HTML. Provided HTML file is it is your app bootstrapper. You don't need to think or deal with HTML. Just use JS/TS.
