### ISSUE TITLE
How to use inconjunction with lerna?

### ISSUE THREAD

**Issue by walleXD** [electron-userland/electron-webpack#57]
Hey all,

I am setting up a project with a monorepo and am trying to figure out how to make sure my packages handled by lerna goes through the same renderer & main webpack pipeline to get compiled.

What's the best way to set this up?

Thanks in advance

**Comment by loopmode** [comment]
I'm also interested in this topic. 
Also, as far as I know, lerna is best at managing packages you publish on npm. In the context of electron-webpack, I'd like to know whether and how lerna can be used to break down apps into multiple smaller projects, and whether it works without publishing everything on npm.

**Comment by walleXD** [comment]
[`yarn workspace`](https://yarnpkg.com/lang/en/docs/workspaces/) is an alternative where you don't need to publish your packages but it is kinda wonky as it hoists all packages to the root by default and many packages break, `electron-webpack` being one of 'em. 

The main struggle with `lerna` atm for me is getting my packages to be compiled by webpack but I believe all `node_modules` files are excluded by default. I am trying to figure out the best way to include my packages and not be handled as an external package.

**Comment by amaurymartiny** [comment]
I managed to create a starter project with lerna + electron webpack: https://github.com/amaurymartiny/cra-lerna-electron.

I don't use yarn workspace, but I think activating it with some `nohoist` config should work too.
