### ISSUE TITLE
Using with electron-next

### ISSUE THREAD

**Issue by walleXD** [electron-userland/electron-webpack#6]
Hi,

I want to use electron next to compile the renderer. How would I use electron-webpack for compiling only the main process?

Thanks alot!

**Comment by develar** [comment]
Interesting, I will support https://github.com/leo/electron-next today or tomorrow. Could you please explain in 2 words why do you want to use electron-next (just to understand, not to advocate :)).

>  I use electron-webpack for compiling only the main process?

You can use only `node_modules/electron-webpack/webpack.main.config.js` to compile app. But yes — `yarn dev` currently requires renderer. Will be fixed.

**Comment by walleXD** [comment]
I am using Nextjs for all most my projects and so it will be easier for me to share code between the webapps and the electron app. Otherwise I will have to wire everything up with react-router, and will lose out alot of the code share between the webapp and electron app.

**Comment by develar** [comment]
Initial docs about support:

* If project has `electron-next` dependency, `electron-webpack dev` will not start webpack-dev-server.

**Comment by develar** [comment]
After reading https://leo.im/2017/electron-next it is clear that additional support for electron-next is not required. Yes, I can change `electron-webpack` to not compile renderer, but it will complicate — for what, if it will be more clear just use `electron-webpack main`

**Comment by develar** [comment]
https://webpack.electron.build/languages-and-frameworks#nextjs

Feel free to request any other support if need.
