### ISSUE TITLE
Url in render to files over 10k

### ISSUE THREAD

**Issue by FantasticFiasco** [electron-userland/electron-webpack#64]
In my project I noticed that an `img` tag stopped rendering the image when I increased the resolution and thus the size. With the new resolution the image was over 10k, which perhaps is the breaking point.

I was wondering how I should solve the issue. The [url-loader](https://github.com/webpack-contrib/url-loader) seems to fall back on the [file-loader](https://github.com/webpack-contrib/file-loader), but according to your code [here](https://github.com/electron-userland/electron-webpack/blob/255e645b8ed4eb7090e2fd396af19eab8464a3fe/packages/electron-webpack/src/targets/RendererTarget.ts#L58), since you don't define a limit the default of 10k is used.

Any idea on whether I should change anything on my end or this is an issue in `electron-webpack`?

**Comment by develar** [comment]
I see https://github.com/FantasticFiasco/searchlight/blob/master/src/renderer/components/app-details.vue ... Since your project is public, I will grab and fix the issue in 2 days.

**Comment by FantasticFiasco** [comment]
Thanks!

**Comment by FantasticFiasco** [comment]
Any way I can help with this issue?

**Comment by FantasticFiasco** [comment]
I've created a branch on which this issue can be viewed: https://github.com/FantasticFiasco/searchlight/tree/issue/175
