### ISSUE TITLE
How to move from electron-compile?

### ISSUE THREAD

**Issue by Lordiuz** [electron-userland/electron-webpack#7]
Hello!

Can you write some tutorial how to move from electron-compile. Because right now this is common way to build app, so it would be very useful. For example right now I have electron-forge with babel, but want to build via electron-webpack, so what main steps I need to do?

**Comment by develar** [comment]
0. [install electron-webpack](https://github.com/electron-userland/electron-webpack#install).
1. Change your project to follow recommended structure (https://github.com/electron-userland/electron-webpack#project-structure). If you don't want to change and want continue to use your existing structure — please file issue: describe your current structure. There is no possibility for now to configure different `src/main` and `src/renderer` directories, but it will be added as soon as will be requested.
2. Add [package scripts](https://github.com/electron-userland/electron-webpack#package-scripts). 
    * Or,  you can use `npx` (bundled with node 8). Like `npx electron-webpack`.
    * Or, you can use webpack CLI and provided [configurations files](https://github.com/electron-userland/electron-webpack/wiki/Configuration-FIles). electron-webpack doesn't restrict you and fully compatible with webpack (`electron-webpack` command is provided only for your convenience — it is nothing more than just a wrapper around webpack CLI).
3. Change (or add) `main` field in the `package.json` to "main.js" Please note — doesn't matter how is named your main file in the sources, here should be `"main.js"`. In the future I will get rid of this requirement.

You can use [slack](https://slackin.electron.build/) to ask quick questions (it can be faster than GitHub issues).

**Comment by develar** [comment]
Please note — if you use electron-builder — please ensure that you use 19.x version. electron-webpack is automatically detected and all required configuration is applied via parent config. e.g. you don't need to configure files or dist out or anything else to make it working for your electron-webpack project. 

For example, electrify has config for electron-builder — https://github.com/electron-userland/electrify/blob/master/package.json#L24, but only to set productName/appId and configure excludes.
