### ISSUE TITLE
@ alias not recognized in SCSS

### ISSUE THREAD

**Issue by chukkwagon** [electron-userland/electron-webpack#72]
### Problem
I am trying to use scss files in my project and the `@` alias is not being recognized by webpack. I added the scss loader dependencies outlined in the [add-ons section of the docs](https://webpack.electron.build/add-ons). My understanding is that the `@` refers to the path of the process that was running (in this case, the renderer). So I expect `@/scss/dimension.scss` to resolve to `src/renderer/scss/dimension.scss`.

### `src/renderer` hierarchy
*some files omitted for readablity
```text
src/renderer/
├── App.vue
├── components
│   ├── Login
│   │   ├── Login.js
│   │   ├── Login.scss
│   │   └── Login.tpl.html
│   ├── Login.vue
├── main.js
├── scss
   ├── color.scss
   ├── dimension.scss
   ├── main.scss
   └── ui.scss

```

### Auth.scss
```scss
@import '@/scss/dimension.scss';
@import '@/scss/ui.scss';
@import '@/scss/color.scss';
```

### Error
```text
ERROR in ./node_modules/css-loader!./node_modules/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-4e68315a","scoped":false,"hasInlineConfig":false}!./node_modules/sass-loader/lib/loader.js!./src/renderer/components/Login/Login.scss
  Module build failed: 
  @import '@/scss/dimension.scss';
  ^
        File to import not found or unreadable: @/scss/dimension.scss.
  Parent style sheet: stdin
        in /home/charlie/dev/work/my-project/src/renderer/components/Login/Login.scss (line 1, column 1)
   @ ./node_modules/vue-style-loader!./node_modules/css-loader!./node_modules/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-4e68315a","scoped":false,"hasInlineConfig":false}!./node_modules/sass-loader/lib/loader.js!./src/renderer/components/Login/Login.scss 4:14-284 13:3-17:5 14:22-292
   @ ./src/renderer/components/Login.vue
   @ ./src/renderer/router/index.js
   @ ./src/renderer/main.js
   @ multi (webpack)-dev-server/client?http://localhost:9080 webpack/hot/dev-server ./node_modules/electron-webpack/vue-renderer-entry.js ./src/renderer/main.js
  Child html-webpack-plugin for "index.html":
       2 assets
         1 module

```

**Comment by chukkwagon** [comment]
Solution was one character smdh. The error is resolved by writing like this (notice the `~`:

```scss
@import '~@/scss/dimension.scss';
@import ~'@/scss/ui.scss';
@import '~@/scss/color.scss';
```

**Comment by loopmode** [comment]
@chukkwagon interesting! ...somewhat surprising too :)

**Comment by chukkwagon** [comment]
@loopmode i don't know why that character is significant and I can't find any documentation for it... but for some reason it works. Do you know if that is a special `webpack` character or something?

**Comment by loopmode** [comment]
Well it makes sense. It's a feature of sass-loader for webpack.

> Just prepend them with a ~ to tell webpack that this is not a relative import

https://github.com/webpack-contrib/sass-loader#imports

So, first with the `~` you tell sass-loader "next part is absolute", then there is the `@` resolved by `electron-webpack` I guess..?

**Comment by chukkwagon** [comment]
I can't believe I didn't look in the `sass-loader` docs, thank you!

**Comment by loopmode** [comment]
welcome :) it's so many parts and layers nowerdays, it's hard to keep track
