### ISSUE TITLE
Revamp Documentation

### ISSUE THREAD

**Issue by SimulatedGREG** [electron-userland/electron-webpack#8]
Similar to how thorough electron-vue's documentation is, I would also like to create thorough documentation for electron-webpack before an official migration of electron-vue to use `electron-wepack`. This module has great potential and great documentation is a must for entry level users! In the end, I would like to explain what some people call *magic* and provide further information about customization.

I see that there is already some inside the `docs/` folder, but would you consider moving the docs to GitBook? Some of the major benefits of moving are better styling /organization and improved SEO optimization to help the module spread around the internet.

**Comment by develar** [comment]
> but would you consider moving the docs to GitBook

Yes, problem was is that official GitBook docs is not clear to help me to understand how to do it, but last month I have looked at your repo :)

Do you also find that it will be better to use GitBook for electron-builder project?

Is it not confusing for you, that such docs, e.g. https://simulatedgreg.gitbooks.io/electron-vue/content/en/, contains only a little icon to project page on github?

**Comment by develar** [comment]
BTW, docs dir is used to generate wiki (https://github.com/electron-userland/electron-webpack/wiki).

**Comment by develar** [comment]
GitHub wiki doesn't have clear advantages over GitBook, and GitBook has the only drawback for me — level of association with project page on github, but it can be fixed using special template. I will configure publishing to GitBook now.

**Comment by SimulatedGREG** [comment]
> Yes, problem was is that official GitBook docs is not clear to help me to understand how to do it, but last month I have looked at your repo :)

For the most part, the GitBook website is the main area where you edit your documentation. Set up isn't super clear, but the project structure found in electron-vue/docs is basically all you need to get it up and running after linking the repo on GitBook.

> Do you also find that it will be better to use GitBook for electron-builder project?

The documentation for `electron-builder` has lived here for a long time, so I'm not sure migrating to GitBook would be completely necessary. But if you were wanting to get official translations of the documentation, then it would the perfect solution. I'm sure there are plenty of community members that would be willing to help with that. electron-vue just got an official Japanese & Chinese translation as of recent.

> Is it not confusing for you, that such docs, e.g. https://simulatedgreg.gitbooks.io/electron-vue/content/en/, contains only a little icon to project page on github?

Not so much. Using GitBook for documentation is a lot more common nowadays. I do believe the Vue.js community may have popularized its usage, but other documentation engines are stirring up as a result. In the end, most people would only find the documentation from the repo to begin with so there isn't much of a *gap* between GitBook and the actual GitHub repo.

**Comment by develar** [comment]
Published to https://webpack.electron.build

Differences to electron-vue gitbook:

* [github-buttons](https://github.com/azu/gitbook-plugin-github-buttons) is used to add "Star" button.
* No language selector. When will be some translation, approach as in the vuejs will be used — for en lang main domain is used — `webpack.electron.build`, for other languages — `de.webpack.electron.build` where `de` it is some lang code. And `Translations` menu in the top navigation bar.
* Deployed on Netlify. Because I prefer short domain name and HTTPS. Netlify is much better to serve static sites than gitbook.

I will change project readme to point to new docs and disable readme a little bit later today/tomorrow. Your feedback about docs is welcome (btw, you are admin on this repo and has push access).

**Comment by SimulatedGREG** [comment]
@develar 

So when updating the `docs/`, are there any extra steps to publishing other than pushing?

**Comment by SimulatedGREG** [comment]
Also, would it be worth creating a simple *quick start* project template? I'm thinking it might be beneficial to entry-level users to be able to clone something similar to https://github.com/electron/electron-quick-start to at least have a project structure.

**Comment by develar** [comment]
To update docs — yarn docs. This command will build docs and push it to repo. You have push permissions to this repo also.

Yes, quick start project make sense, I will add it.

**Comment by SimulatedGREG** [comment]
### Documentation topics [WIP]

- [ ] Introduction
  Front facing **readme.md**.
- [ ] Core Concepts (working title)
  Describe `electron-webpack` package itself, how it works, and how it can be used outside of CLI for custom usage.
- [ ] Development
  Describe webpack setup (HMR, debugging, etc).
  - [ ] Add-ons (working title)
    Describe usage of extra modules like TypeScript, Less, Next.js. 
  - [ ] Global Configuration
    Describe usage of `electronWebpack` in **package.json**.
- [ ] Project Structure
    Describe project structure, its configurations, and what is optional.
- [ ] Building
  **TBD**
