### ISSUE TITLE
Can't debug with vscode

### ISSUE THREAD

**Issue by navono** [electron-userland/electron-webpack#80]
# Environment
VSCode: v1.19.1
OS: Windows 10
Node: v8.9.3

# Operating steps
First I use the sample code from [electron-quick-start-typescript](https://github.com/electron/electron-quick-start-typescript.git]), and add launch.json like this:
```js
{
  // 使用 IntelliSense 了解相关属性。 
  // 悬停以查看现有属性的描述。
  // 欲了解更多信息，请访问: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "type": "node",
      "request": "launch",
      "name": "Electron: Main",
      "protocol": "inspector",
      "cwd": "${workspaceRoot}/dist",
      "runtimeExecutable": "${workspaceRoot}/node_modules/.bin/electron",
      "windows": {
          "runtimeExecutable": "${workspaceRoot}/node_modules/.bin/electron.cmd"
      },
      "program": "${workspaceRoot}/src/main/main.ts",
      "runtimeArgs": [
        "--enable-logging",
        "--remote-debugging-port=9223",
      ],
      "sourceMaps": true,
      "outFiles": [
          "${workspaceRoot}/dist/**/*.js"
      ],
      "internalConsoleOptions": "openOnSessionStart",
      "console": "integratedTerminal",
    },
    {
      "name": "Electron: Renderer",
      "type": "chrome",
      "request": "attach",
      "port": 9223,
      "webRoot": "${workspaceRoot}/dist",
      "timeout": 15000,
      "sourceMaps": true,
    }
  ],
  "compounds": [
    {
      "name": "Electron: All",
      "configurations": [
          "Electron: Main",
          "Electron: Renderer"
      ]
    }
  ]
}
```

When trigger F5, everything is fine, the breakpoints also breaks. But when I add `eletron-webpack`, vscode debugger is broken. It shows:
```json
Cannot launch program 'e:\sourcecode\frontend\electron-ts-test\src\main\main.ts' because corresponding JavaScript cannot be found.
```

package.sjon:
```js
  "dependencies": {
    "source-map-support": "^0.5.0"
  },
  "devDependencies": {
    "electron": "^1.7.10",
    "electron-builder": "^19.50.0",
    "electron-webpack": "^1.11.0",
    "electron-webpack-ts": "^1.2.0",
    "tslint": "^5.8.0",
    "typescript": "^2.6.2",
    "webpack": "^3.10.0"
  },
  "resolutions": {
    "webpack-sources": "1.0.1"
  }
```

tsconfig.json:
```js
{
  "compilerOptions": {
    "module": "commonjs",
    "noImplicitAny": true,
    "sourceMap": true,
    "outDir": "dist",
    "baseUrl": ".",
    "paths": {
      "*": ["node_modules/*"]
    }
  },
  "include": [
    "src/**/*"
  ]
}
```
Am I miss something or lack of some configuration?
Thank you.

**Comment by navono** [comment]
I change the launch.json from
```js
"program": "${workspaceRoot}/src/main/main.ts",
```
to 
```js
"program": "${workspaceRoot}/dist/main/main.js",
```
Trigger F5, vs code debugger works fine. But the breakpoints can't trigger. It prompt:
```js
Breakpoint Ignored Because Generated Code Not Found
```
I check the dist folder. .map files has generated.

**Comment by navono** [comment]
Currently, I'm not use `electron-webpack` anymore. So close.

**Comment by davidmdem** [comment]
For anyone else stumbling here, I have had success debugging the main process with vscode using the following configuration:

```
{
    "type": "node",
    "request": "launch",
    "name": "Launch and Debug",
    "runtimeExecutable": "yarn",
    "runtimeArgs": [
        "dev"
    ],
    "autoAttachChildProcesses": true,
    "internalConsoleOptions": "openOnFirstSessionStart",
    "console": "integratedTerminal"
}
```

This won't work for the renderer - I have been using the `Sources -> webpack://` area in Chrome's dev tools.

**Comment by yantze** [comment]
`electron-webpack dev` can instead of `yarn dev`, just like below:

```json
{
    "type": "node",
    "request": "launch",
    "name": "Launch and Debug",
    "runtimeExecutable": "${workspaceRoot}/node_modules/.bin/electron-webpack",
    "runtimeArgs": [
        "dev"
    ],
    "autoAttachChildProcesses": true,
    "internalConsoleOptions": "openOnFirstSessionStart",
    "console": "integratedTerminal"
}
```

**Comment by parliament718** [comment]
I can't for the life of me get this working. electron-webpack trying to connect to the debugger on a random port every time. I have the following launch.json

```
{
	"name": "Debug main process",
	"type": "node",
	"request": "launch",
	"stopOnEntry": true,
	"args": [
		"--inspect-brk=9229"
	],
	"cwd": "${workspaceRoot}/client",
	"runtimeExecutable": "${workspaceRoot}/client/node_modules/.bin/electron-webpack",
	"runtimeArgs": [
		"dev",
		"--inspect-brk=9229"
	],
	"env": {
		"ELECTRON_ARGS": "[\"--inspect-brk=9229\"]"
	},
	"sourceMaps": true,
	"autoAttachChildProcesses": true,
	"internalConsoleOptions": "openOnSessionStart",
	"console": "integratedTerminal"
},
```

I have an .env file with ELECTRON_ARGS=["--inspect-brk=9229"] and as you can see I'm trying to pass 9229 as the port in just about every way possible but when I hit run the command that runs is 

> cd /Users/user/Documents/code/botmain/client ; env 'ELECTRON_ARGS=["--inspect-brk=9229"]' /Users/user/Documents/code/botmain/client/node_modules/.bin/electron-webpack dev --inspect-brk=9229 **--inspect-brk=19184** --inspect-brk=9229 

Where did this port 19184 come from? It's random everytime and vscode responds with 

> Cannot connect to runtime process, timeout after 10000 ms - (reason: Cannot connect to the target: connect ECONNREFUSED 127.0.0.1:**19184**).

Has anyone been able to get debugging working for their main process?

I cant get it working with pure electron either, having the same problem outlined by OP:

`"Cannot launch program <path> because corresponding JavaScript cannot be found"`
