### ISSUE TITLE
Issue of importing submodules.

### ISSUE THREAD

**Issue by s-shin** [electron-userland/electron-webpack#81]
I tried to use [CodeMirror](https://github.com/codemirror/codemirror) in the project constructed by electron-webpack, then faced this incomprehensible issue.

I created [the minimal project](https://github.com/s-shin/electron-webpack-issue-of-importing) to get reproduction of this issue, please see it.

In my research, the `CodeMirror` instance imported in plugins (e.g. [codemirror/mode/javascript/javascript](https://github.com/codemirror/CodeMirror/blob/5.33.0/mode/javascript/javascript.js#L6)) seems to be different from the one got by `required("codemirror")` [here](https://github.com/s-shin/electron-webpack-issue-of-importing/blob/master/src/renderer/index.js#L4).

I'm guessing something in build phase causes this problem, but I haven't detected it yet.

**Comment by s-shin** [comment]
I completely understood the reason why this problem occurs.

## What occurred?

Two different instances of codemirror's main module are referred: one from the [external](https://webpack.js.org/configuration/externals/) and another from the bundled.

The former can be got by `import * as CodeMirror from "codemirror"` (or `const CodeMirror = require("codemirror")`), because, as [the document](https://webpack.electron.build/configuration#white-listing-externals) says, electron-webpack treats all modules listed in `dependencies` of package.json as [externals](https://webpack.js.org/configuration/externals/).

The latter will be loaded by importing the submodules of codemirror package (e.g. `import "codemirror/mode/javascript/javascript"`), because they are not external and the codemirror's main module [imported by relative path in each of them](https://github.com/codemirror/CodeMirror/blob/5.33.0/mode/javascript/javascript.js#L6) isn't also external.

Thus, the codemirror's plugin system is broken without special configuration.

## How to resolve it?

There are two solutions. IMO, the second solution will be recommended.

### 1. Exclude all modules related to codemirror from externals.

We can use [`electronWebpack.whiteListedModules`](https://webpack.electron.build/configuration#white-listing-externals) option.

If using third party packages importing codemirror (e.g. react-codemirror2), they should also be appended there.

For example:

```json
"electronWebpack": {
  "whiteListedModules": [
    "codemirror",
    "react-codemirror2"
  ]
}
```

### 2. Include all modules related to codemirror into externals.

We can use [the modification system of webpack configurations](https://webpack.electron.build/modifying-webpack-configurations) or (undocumented)
 [`electronWebpack.externals`](https://github.com/electron-userland/electron-webpack/blob/v1.11.0/packages/electron-webpack/src/main.ts#L268-L269) option.

In almost all cases, the former will be easier because regex is available.

Example of the former:

```js
// webpack.renderer.additions.js
module.exports = {
  "externals": [
    /^codemirror\/(mode|keymap)\/.+$/,
  ]
};
```

```json
"electronWebpack": {
  "renderer": {
    "webpackConfig": "webpack.renderer.additions.js"
  }
}
```

Example of the latter:

```js
"electronWebpack": {
  "externals": [
    "codemirror/mode/javascript/javascript",
    "codemirror/mode/gfm/gfm",
    "codemirror/keymap/vim"
  ]
}
```

---

I'll close this issue, but hope it helps someone :)

**Comment by davidwinter** [comment]
Thanks @s-shin - have been spending all morning trying to figure out why it wasn't working, and finally found your issue and resolution and :boom: sorted!!
