### ISSUE TITLE
Specify electronArgs in config file

### ISSUE THREAD

**Issue by d21d3q** [electron-userland/electron-webpack#85]
I wanted to pass flag `--diable-pinch` flag directly to electron so that it won't react for pinch zooming while running app in fullscreen on touchscreen, and I found that it is possible only by setting environment variable `ELECTRON_ARGS='["--disable-pinch"]'` 
Code responsible for it resides [here](https://github.com/electron-userland/electron-webpack/blob/2eaa68ec0d749233c0f36b6d528bda4c126ba88b/packages/electron-webpack/src/dev/dev-runner.ts#L56)

It would be nice to pass such argument from config file.

**Comment by loopmode** [comment]
I agree that it would be very nice to set electronArgs via config file. 
While we can specify args in package scripts, e.g. using `cross-env`, that doesn't scale well. 

Btw @d21d3q in our project, we disabled pinch zoom from code, in the renderer process:
```
// prevent pinch zoom
const { webFrame } = require('electron');
webFrame.setVisualZoomLevelLimits(1, 1);
webFrame.setLayoutZoomLevelLimits(0, 0);
```
Feels as if the `--disable-pinch` is the better way of doing it, of course - but it also contronts with the args hassle.

**Comment by develar** [comment]
Well... problem is that the only "right" way is that exactly as @loopmode suggested. Because for production app you cannot pass command line args without additional bat wrapper (for windows).
So, I closed issue — PR will be accepted, but it will be not implemented by me due to non-production ready fact described above.

**Comment by develar** [comment]
Please see https://github.com/electron/electron/blob/master/docs/api/app.md#appcommandlineappendargumentvalue and https://github.com/electron/electron/blob/master/docs/api/app.md#appcommandlineappendswitchswitch-value

**Comment by loopmode** [comment]
hah, good one with the appendSwitch! 
We do something like this in the main process:
```
import { app } from 'electron';
app.commandLine.appendSwitch('--enable-precise-memory-info');
```
and it works fine. Not sure about `--disable-pinch` but @d21d3q you should try it, might work!
