### ISSUE TITLE
No Babel plugins

### ISSUE THREAD

**Issue by marcus-sa** [electron-userland/electron-webpack#86]
I've struggled with this library for days, and I must say it's pretty broken, or at least useless when it comes down to configuration.

First of all there's no way to include your babel plugins, even if you include a webpackConfig in the electronWebpack in your package.json, you can't use "babel-loader" twice and actually set the plugins, neither does the [extending as a library](https://webpack.electron.build/extending-as-a-library) properly work, so for me it's just too little outcome for too much input.

HMR doesn't work either, even if you don't specify custom directives #84

**Comment by develar** [comment]
> All direct dev dependencies babel-preset-* and babel-plugin-* are automatically configured also.

So, it doesn't work?
