### ISSUE TITLE
Error in 0.14.0

### ISSUE THREAD

**Issue by FantasticFiasco** [electron-userland/electron-webpack#9]
My build script has reported [an error](https://travis-ci.org/FantasticFiasco/axis-searchlight/builds/265881923) regarding running `electron-webpack dll`.

I did not spot any breaking changes in the release notes, what am I doing wrong?

**Comment by FantasticFiasco** [comment]
I've now got a [new error](https://travis-ci.org/FantasticFiasco/axis-searchlight/builds/266237157) but I think that is because I am lacking some configuration. I will investigate during the weekend. Thanks for the quick feedback!

**Comment by develar** [comment]
If you don't have DLL configurations, do not add `"postinstall": "electron-webpack dll"`

**Comment by develar** [comment]
But yes, probably we need to change error to warning.

**Comment by develar** [comment]
But actually, you have. Will be investigated now.

**Comment by develar** [comment]
Sorry for incovenience, test suite currently doesn't catch such errors. Fixed in 0.14.2

**Comment by FantasticFiasco** [comment]
0.14.2 did the trick, thanks!

No need for apologizes, I value the time you spend in building a more efficient development environment for the rest of us, and you should think of me as an early adopter that happily report any problems I encounter.
