### ISSUE TITLE
Unable to build project

### ISSUE THREAD

**Issue by asaf050** [electron-userland/electron-webpack#94]
Hello ,

I'm coming across an issue when try to build the project.
I'm getting the following error:
`/home/ubuntu/Workspace/Projects/electron-webpack-quick-start/node_modules/webpack-sources/node_modules/source-map/lib/source-map-generator.js:276
        throw new Error(
              ^
Error: original.line and original.column are not numbers -- you probably meant to omit the original mapping entirely and only map the generated position. If so, pass null for the original mapping instead of an object with empty or null values.`

node: 8.9.4
npm: 5.6.0
yarn: 1.3.2

Step to reproduce:

1. Clone electron-webpack-quick-start
2. Run yarn
3. Run yarn dist

**Comment by loopmode** [comment]
This is a known issue and there is a workaround, see https://github.com/mozilla/source-map/issues/304#issuecomment-343827956

**Comment by dracan** [comment]
To save everyone having to track down the workaround, just put `"webpack-sources": "1.0.1"` in your package.json to force that version until this is fixed.

**Comment by delaneyj** [comment]
I'm windows with a working (for dev) TS/Vue setup.  Adding `"webpack-sources": "1.0.1"` to `package.json` deleted `node_modules` and rebuilt.  Still getting this same error.  Could I be missing something else?

```
{
  "name": "electron-webpack-quick-start",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "dev": "electron-webpack dev",
    "compile": "electron-webpack",
    "dist": "yarn compile && electron-builder",
    "dist:dir": "yarn dist --dir -c.compression=store -c.mac.identity=null"
  },
  "dependencies": {
    "@types/animejs": "^2.0.0",
    "@types/three": "^0.89.10",
    "animejs": "^2.2.0",
    "source-map-support": "^0.5.3",
    "three": "^0.90.0",
    "vue-property-decorator": "^6.0.0",
    "vue-router": "^3.0.1",
    "vuex": "^3.0.1",
    "webpack-sources": "1.0.1"
  },
  "devDependencies": {
    "electron": "1.7.12",
    "electron-builder": "^19.56.0",
    "electron-webpack": "1.12.1",
    "electron-webpack-ts": "^1.3.0",
    "electron-webpack-vue": "^1.3.0",
    "node-sass": "^4.7.2",
    "sass-loader": "^6.0.6",
    "typescript": "^2.7.2",
    "vue": "^2.5.13",
    "webpack": "^3.10.0"
  }
}
```

**Comment by dracan** [comment]
@delaneyj Not sure, but I'm using Windows and Vue (but without Typescript), which does work. The project I'm using it for is here: https://github.com/dracan/tomatoad if that helps at all.

**Comment by loopmode** [comment]
Hmm @dracan has it in `devDependencies`, while you have it in `dependencies`.
I would still suggest using `resolutions` instead, because you don't know what your sub-dependencies might depend on! They might still use their own version, desprite of what your won project depends on.

See https://yarnpkg.com/lang/en/docs/selective-version-resolutions/#toc-why-would-you-want-to-do-this

**Comment by develar** [comment]
https://github.com/electron-userland/electron-webpack-quick-start/blob/master/package.json#L21

**Comment by loopmode** [comment]
See https://github.com/mozilla/source-map/issues/304#issuecomment-385227103
