### ISSUE TITLE
Running a production build without packing

### ISSUE THREAD

**Issue by funwithtriangles** [electron-userland/electron-webpack#95]
`electron-webpack dev` is great! I can quickly load up my electron app without the need to package it into an app. 

I'd love similar functionality but with the node environment set to `production`. I have things I need to test once the app is in production and right now the only way I can test is to package my app and then run it, using `electron-builder`. I'm aware I can compile the app without packaging via `electron-webpack` but not sure how I can run what is compiled afterwards.

Thanks!

**Comment by develar** [comment]
To quickly test production, just do `yarn dist:dir` (task `yarn dist --dir -c.compression=store -c.mac.identity=null`, see example https://github.com/electron-userland/electron-webpack-quick-start/blob/master/package.json) and then run file `dist/linux-unpacked/your_app` (or `dist/mac/your_app.app`).

I am not sure that it is useful and will be widely used to add special `electron-webpack prod` task.

**Comment by loopmode** [comment]
On windows you get a `dist/win_unpacked/your_app.exe` as well. 
I was about to write the same thing: Not sure how useful this is. 
It does allow you to skip the install process and just launch the app, but you still have to wait for the full build process to finish. 
And while skipped installation takes just seconds, the build process itself naturally takes quite a while, even for a simple app.

**Comment by develar** [comment]
> takes quite a while, even for a simple app.

No, if `--dir`. Should be quite fast.

**Comment by funwithtriangles** [comment]
Your example is exactly what I was looking for, not sure how I missed that in the docs! For what it's worth, it's easy enough to automatically open the newly compiled production app (OSX):

`yarn dist -- --dir -c.compression=store -c.mac.identity=null && open dist/mac/app_name.app/`

I totally agree with `electron-webpack prod` being unnecessary.

**Comment by develar** [comment]
> I totally agree with electron-webpack prod being unnecessary.

Yep. I want to reduce magic level. User should understand at least basics of used tools. It is very easy to write own `task` and fully understand what's going on and how does it work.

**Comment by pvh** [comment]
I just came across this idea here. It might be nice to include it in the example scripts or somewhere else in the documentation so that it's better discoverable. Thanks for a nice project!
