### ISSUE TITLE
Question: Creating other windows?

### ISSUE THREAD

**Issue by dracan** [electron-userland/electron-webpack#98]
Hi. I have this working with a single window, but my app needs to support multiple windows - eg. 'settings' and 'about' windows, etc. These windows are opened by system-tray menu items - so get created from the main process. Is this possible with electron-webpack?

**Comment by loopmode** [comment]
I was doing some research in the same direction. You can do this simply using URLs - you don't see them, but they still work in electron :)
You can use your `renderer/index.js` as a kind of "app shell" and load the correct "app" based on the URL.
In my case, I will be using react and react-router, with a hash-based solution (hashes work better in electron for me, especially with HMR), so I will have the tray icon launch a new window with e.g. `index.html#settings` or `#about`.

**Comment by dracan** [comment]
Oh nice! Just tried this, and it works perfectly! :) Thank you so much replying with your findings :)

**Comment by dracan** [comment]
In case anyone else is trying to solve the same problem - the code that I've done this for is here ...

https://github.com/dracan/tomatoad
